### ISSUE TITLE
Thumbnail / featured images

### ISSUE THREAD

**Issue by mnwalker** [GrafiteInc/CMS#100]
Is this possible, or if not is it something that would be planned?

Being able to work a default image into the pages/blogs etc is the one thing that seems missing for me from an otherwise great package.
The images would be used as thumbnails on the view all pages and as header images on show single entry.

If it's agreed that this would be beneficial then I could help with a pull request, or if not desired in core will just work on a custom modification on my instance.

**Comment by mlantz** [comment]
Oh like a hero image? Yeah that would be cool to add that. I'll put it on my list. Thanks for the suggestion.
