### ISSUE TITLE
image uploading error

### ISSUE THREAD

**Issue by developr007** [GrafiteInc/CMS#101]
![1](https://user-images.githubusercontent.com/30045765/33014570-c3fb512a-ce0d-11e7-8d8e-8381c313c672.jpg)
![2](https://user-images.githubusercontent.com/30045765/33014577-c7f12ca0-ce0d-11e7-9764-67e0f76986a8.jpg)

**Comment by mlantz** [comment]
Do you have a collection of images currently working in the Image management section?
