### ISSUE TITLE
Mysql / Mariadb 5.5 Specified key was too long

### ISSUE THREAD

**Issue by CoolGoose** [GrafiteInc/CMS#102]
Hi Guys,

Using MariaDB 5.5.56 and just running the install script fails on a migration.
At a quick look at it it seems that using utf8mb4 makes the max length 191 chars for varchar making the email field in the users table to need to have a slight adjustment (and maybe others).

I can check all migrations if there's any that need the restriction but I'm not sure if you guys support mysql 5.5 or not (issue is 'fixed' in 5.7+ it seems https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes )

**Comment by mlantz** [comment]
By default Quarx doesnt actually handle the user migration stuff, it just uses the default Laravel one. So for now I'm not sure there is anything that can be done. We could update the documentation to be more specific about that though, thanks.

**Comment by CoolGoose** [comment]
@mlantz I'll check laravel's repo maybe they have an open bug request, if not i'll open a new one and cross reference.

**Comment by vblinden** [comment]
Add `Schema::defaultStringLength(191);` to AppServiceProvider.php. See https://laravel.com/docs/5.5/migrations#indexes
