### ISSUE TITLE
Class Yab\Quarx\Models\Route:list does not exist

### ISSUE THREAD

**Issue by Nowi5** [GrafiteInc/CMS#105]
Hi all,

when I run "artisan route:list (List all registered routes)" I get the error "Class Yab\Quarx\Models\Route:list does not exist". Can you please have a look?

Environment: PHP 7, Laravel + Quarx newst version, but complex installation

Thank you.

**Comment by Nowi5** [comment]
See Pull Request #131

**Comment by mlantz** [comment]
Thank you again @Nowi5 for your feedback on this one, I had fixed it a couple days prior to your PR but was waiting for v3.1 release to get it out. Thanks again for your contributions
