### ISSUE TITLE
RoutePrefix ignored when adding first link to menu

### ISSUE THREAD

**Issue by Nowi5** [GrafiteInc/CMS#108]
Hi all,

when I add the first link to a newly created menu, the post fails with 404.
The page called is "quarx/menus/1/edit" but my prefix URL is different.

Can you please double check?

Thank you.

**Comment by galenskap** [comment]
I have this issue too: if my admin prefix is set to "quarx", there is no 404. However if I set it to "admin" in config file, the redirection after links saving does not use the new prefix.
