### ISSUE TITLE
Input validation missing for FAQ

### ISSUE THREAD

**Issue by Nowi5** [GrafiteInc/CMS#110]
Hi all,

I can insert a FAQ question without an answer, which ends in a SQL error.

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'answer' cannot be null (SQL: insert into `faqs` (`question`, `answer`, `published_at`, `is_published`, `updated_at`, `created_at`) values (Test, , 2018-01-20 22:38:59, 0, 2018-01-20 22:38:59, 2018-01-20 22:38:59))

Maybe you should consider input validation for all models.

Thank you for double checking.

**Comment by mlantz** [comment]
This was resolved in v3.0.0
