### ISSUE TITLE
How to add a new language to the site?

### ISSUE THREAD

**Issue by horstleung** [GrafiteInc/CMS#114]
I have followed the doc, adding two languages to quarx.php and edited the page content.

![image](https://user-images.githubusercontent.com/1083049/36092393-27acfda8-1022-11e8-9404-fed8c4762862.png)

However, I can only access the en and tw content with the links:
http://localhost/en/page/hello-world-page
http://localhost/tw/page/hello-world-page

but not

http://localhost/fr/page/hello-world-page

It would show the tw content

In the db:
![image](https://user-images.githubusercontent.com/1083049/36092461-699be3f0-1022-11e8-845e-5ca97b02757a.png)

![image](https://user-images.githubusercontent.com/1083049/36092488-80d8786c-1022-11e8-9941-865e3929b440.png)

**Comment by mlantz** [comment]
Hey so it looks like the middleware isnt working nice with Laravel 5.5+ change up the QuarxLanguage Middleware to the following handler method

```
    public function handle($request, Closure $next)
    {
        if (Cookie::has('language')) {
            Config::set('app.locale', Cookie::get('language'));
        }

        return $next($request);
    }
```

Then make sure you do `use Illuminate\Support\Facades\Cookie;` at the top. That should fix the language

**Comment by horstleung** [comment]
I have changed the file QuarxLanguage.php 
from:
![image](https://user-images.githubusercontent.com/1083049/36415459-e944972a-1660-11e8-852d-464dbd23fc38.png)

to
![image](https://user-images.githubusercontent.com/1083049/36415446-e070f2d8-1660-11e8-9691-88df2d776a2a.png)

However, it doesn't work in my case.

**Comment by mlantz** [comment]
Can you confirm that the middleware is being called?

**Comment by horstleung** [comment]
Yes, it is being called.
![image](https://user-images.githubusercontent.com/1083049/36654367-0e890c56-1af7-11e8-869b-cad97a362e98.png)

**Comment by mlantz** [comment]
Was this ever resolved @fattomhk?

**Comment by mlantz** [comment]
I am closing this due to lack of feedback. Translations and languages are in review at this time #132
