### ISSUE TITLE
Quarx clobbering existing '/' route

### ISSUE THREAD

**Issue by anishpdoshi** [GrafiteInc/CMS#117]
I have an index route, named '/', in routes/web.php, but with  the addition of Quarx i'm getting an error:

development.ERROR: Route [/] not defined.

Additionally, the existing index page has changed into a quarx starter template.

Is this intentional? i'd like to not have quarx overwrite existing pages

**Comment by mlantz** [comment]
If you used the 'simple setup' the command will overwrite things and cause breakages. It explicitly states to only use that if its a fresh Laravel app. Based on what you're saying, following the complex setup https://docs.grafite.ca/cms/#complex-setup
