### ISSUE TITLE
'mkdir() permission denied error' when trying to navigate to /quarx/dashboard

### ISSUE THREAD

**Issue by anishpdoshi** [GrafiteInc/CMS#118]
Getting the following error on laravel 5.5 when trying to go to /quarx/dashboard:

elopment.ERROR: mkdir(): Permission denied (View: /var/www-test/resources/views/vendor/quarx/dashboard/analytics-internal.blade.php)

Any new permissions i need to add?

**Comment by mlantz** [comment]
This looks like an issue with your workspace setup or server permissions. You may have to examine those.
