### ISSUE TITLE
Uncaught ReferenceError: _setDashboard is not defined

### ISSUE THREAD

**Issue by shabaz-ejaz** [GrafiteInc/CMS#120]
I keep getting this error:

![untitled](https://user-images.githubusercontent.com/29374282/36902919-0ad187c0-1e24-11e8-8b8d-337679ec71c9.png)

It is coming from `vendor\yab\quarx\src\Assets\js\quarx.js`:

 ```
$(window).resize(function(){
        _setDashboard();
    });

    _setDashboard();
```

I have no idea what this is supposed to do but it stops other JS from loading so my application breaks.

**Comment by mlantz** [comment]
Looks like my recent updates broke the dashboard portion, I'll have a fix out very soon

**Comment by shabaz-ejaz** [comment]
Any fix for this yet?

**Comment by mlantz** [comment]
Unfortunately @shabaz-ejaz I had to abandon the name Quarx and Yab abruptly rebrand the packages and release them under a new name. I have been working extensively on this. It is not an issue in the latest version of Grafite CMS but switching from Quarx to Grafite CMS does require several steps. I'm currently writing a blog entry on how to achieve this. I apologize for the inconvenience.
