### ISSUE TITLE
Updating with the name change breaks installs

### ISSUE THREAD

**Issue by ajoy39** [GrafiteInc/CMS#124]
Since the org name change on Github I've been getting warnings when trying to update our dependencies because Quarx still has the old package names listed as dependencies. Example:

```
Package yab/formmaker is abandoned, you should avoid using it. Use grafite/formmaker instead.
```

This morning I ran composer update and it updated yab/formmaker to version 1.3 and now the build is broken entirely, all of my tests fail with the following

```
250) UserTest::user_unsubscribe_from_mail
Error: Class 'Yab\FormMaker\FormMakerProvider' not found
```

Yab/Formmaker is not a dependency I have listed in my composer.json file, it's a dependency of quark. So Quarx's composer file needs to be updated to reflect the organizational name change as well.

**Comment by ajoy39** [comment]
The only way to fix this now that Quarx has been adandoned is to add a hard depency version for yab/formmaker to your composer.json file. Just lock it to version 1.2.10, if it updates to 1.3 your build will be broken and the migration to Quarx 3/GrafiteCMS is non-trivial.

**Comment by mlantz** [comment]
I'm sorry about that @ajoy39 It was a rather sudden need to rebrand the packages and switch the package names themselves. I will do my best to improve communication on how packages may change in the future. I'm currently writing a more detailed upgrade guide to switch from Quarx to Grafite CMS. Again I apologize that the changes caused breaks in your code base.

**Comment by mlantz** [comment]
I have posted updates to the docs on how to handle some parts of the transition from Quarx to Grafite CMS. https://docs.grafite.ca/cms/upgrade/

**Comment by martsie** [comment]
In the future could you please fork things as new package names and leave the old ones - having to development work right before a release after testing just to get composer install to run again is threw our schedule out of whack a bit.

**Comment by mlantz** [comment]
Again I apologize for the inconvenience, it was never intended to be such a switch, and I had to rush to get everything moved over, and I wasn't too sure what the best strategy was. The process has taught me many things.
