### ISSUE TITLE
Class 'Yab\FormMaker\FormMakerProvider' not found

### ISSUE THREAD

**Issue by vladstroeandrei** [GrafiteInc/CMS#126]
Hello, after i tried to update my composer i got this error and now it's not letting me to use even artisan command, the only way to get rid of this error is by removing quarx but right now this is not an option.

`Generating autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Application.php line 635:

  Class 'Yab\FormMaker\FormMakerProvider' not found

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
`

Thank you.

**Comment by IManAsap** [comment]
I have the same error by installing Quarx on a new project Laravel 5.5.* :

composer require yab/quarx
Using version ^2.4 for yab/quarx
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 30 installs, 0 updates, 0 removals
  - Installing donatj/phpuseragentparser (v0.5.3): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.0): Loading from cache
  - Installing stichoza/google-translate-php (v3.2.13): Loading from cache
  - Installing intervention/image (2.4.1): Loading from cache
  - Installing league/commonmark (0.16.0): Loading from cache
  - Installing graham-campbell/markdown (v8.1.0): Loading from cache
  - Installing mtdowling/jmespath.php (2.4.0): Loading from cache
  - Installing aws/aws-sdk-php (3.52.28): Loading from cache
  - Installing league/flysystem-aws-s3-v3 (1.0.18): Loading from cache
  - Installing google/apiclient (v1.1.8): Loading from cache
  - Installing spatie/laravel-analytics (1.4.1): Loading from cache
  - Installing tedivm/jshrink (v1.3.0): Loading from cache
  - Installing natxet/cssmin (v3.0.6): Loading from cache
  - Installing devfactory/minify (1.0.7): Loading from cache
  - Installing yab/laratest (v0.1.1): Loading from cache
  - Installing yab/cerebrum (v1.1.3): Loading from cache
  - Installing yab/crypto (v1.0.6): Loading from cache
  - Installing laravelcollective/html (v5.5.3): Loading from cache
  - Installing doctrine/collections (v1.5.0): Loading from cache
  - Installing doctrine/cache (v1.7.1): Loading from cache
  - Installing doctrine/annotations (v1.6.0): Loading from cache
  - Installing doctrine/common (v2.8.1): Loading from cache
  - Installing doctrine/dbal (v2.6.3): Loading from cache
  - Installing yab/formmaker (v1.3.0): Loading from cache
  - Installing yab/crudmaker (v1.3.0): Loading from cache
  - Installing yab/laracogs (v2.3.4): Loading from cache
  - Installing yab/quarx (v2.4.6): Loading from cache
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
league/commonmark suggests installing league/commonmark-extras (Library of useful extensions including smart punctuation)
aws/aws-sdk-php suggests installing aws/aws-php-sns-message-validator (To validate incoming SNS notifications)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
Package yab/laratest is abandoned, you should avoid using it. No replacement was suggested.
Package yab/cerebrum is abandoned, you should avoid using it. No replacement was suggested.
Package yab/crypto is abandoned, you should avoid using it. Use grafite/crypto instead.
Package yab/formmaker is abandoned, you should avoid using it. Use grafite/formmaker instead.
Package yab/crudmaker is abandoned, you should avoid using it. Use grafite/crudmaker instead.
Package yab/laracogs is abandoned, you should avoid using it. Use grafite/builder instead.
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Application.php line 635:

  Class 'Yab\FormMaker\FormMakerProvider' not found


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by IManAsap** [comment]
Resolute by changing 
1) "use Yab\FormMaker\FormMakerProvider;" by "use Grafite\FormMaker\FormMakerProvider; ' in"\vendor\yab\laracogs\src\LaracogsProvider.php"
2) "$this->app->register(\Yab\FormMaker\FormMakerProvider::class);" by "$this->app->register(\Grafite\FormMaker\FormMakerProvider::class);" in "\vendor\yab\crudmaker\src\CrudMakerProvider.php"

I am going to validate the solution and probably to create a fork

**Comment by shabaz-ejaz** [comment]
@IManAsap Is there a reason why Quarx has been abandoned? There is no information regarding the change at all. I think that was a very dangerous move considering how many people would have had Quarx and laracogs in the project dependencies. 

Can you provide an insight as to what's gone on and possible fixes for people still using Quarx? Also the docs have all disappeared for Laracogs which is not nice at all.

**Comment by mlantz** [comment]
In the GitterIM channels as well as packages on a whole got rebranded in order to maintain them. All docs moved to https://docs.grafite.ca etc. Quarx, Laracogs, FormMaker, CrudMaker etc are all going to be maintained with their new branding. As a conseqence of this packages had to be abandoned and switched to the new brand.

**Comment by shabaz-ejaz** [comment]
@mlantz You didn't answer my question. **possible fixes for people still using Quarx**?

**Comment by shabaz-ejaz** [comment]
@mlantz Did you read my previous comment?

**Comment by mlantz** [comment]
@shabaz-ejaz Please read the documentation provided in on https://docs.grafite.ca, it has some further notes on upgrading and the name changes, and please stop commenting on closed issues.

**Comment by shabaz-ejaz** [comment]
@mlantz I cannot find any page that has further notes on upgrading. Can you send me a specific page link that covers this in detail? and stop ignoring common important comments on issues that clearly still arise from your `abrupt` name change.
