### ISSUE TITLE
fresh install `Can't locate path: <...\vendor\grafite\cms\src/PublishedAssets/Migrations>`

### ISSUE THREAD

**Issue by khooz** [GrafiteInc/CMS#127]
Hi,
I have freshly installed Laravel 5.6 and following instruction on installing Grafite CMS, upon `artisan vendor:publish` I get this output:

    > php artisan vendor:publish --provider="Grafite\Cms\GrafiteCmsProvider"
    Copied Directory [\vendor\grafite\cms\src\PublishedAssets\Views\themes] To [\resources\themes]
    Copied Directory [\vendor\grafite\cms\src\PublishedAssets\Controllers] To [\app\Http\Controllers\Cms]
    Can't locate path: <path\to\project\vendor\grafite\cms\src/PublishedAssets/Migrations>
    Copied Directory [\vendor\grafite\cms\src\PublishedAssets\Middleware] To [\app\Http\Middleware]
    Copied Directory [\vendor\grafite\cms\src\PublishedAssets\Routes] To [\routes]
    Copied Directory [\vendor\grafite\cms\src\PublishedAssets\Config] To [\config]
    Copied Directory [\vendor\grafite\cms\src\Views] To [\resources\views\vendor\cms]
    Publishing complete.

I gather that migrations are under `grafite\cms\src\Migrations`. Can you please elaborate? I am fairly aquinted with QuarxCMS package but new to Grafite.

Thanks!

WAMP
Windows 10 Pro
Apache >= 2.4
MariaDB >=10.2
PHP >= 7.2

Laravel >= 5.6
w/ predis/predis

**Comment by mlantz** [comment]
That may be a broken part from some of the recent changes. I'll review this.

**Comment by mlantz** [comment]
Fix is coming in the next release

**Comment by mlantz** [comment]
Resolved in v3.1
