### ISSUE TITLE
Image upload fails with no visible error using uploader but fails with exception on edit.

### ISSUE THREAD

**Issue by alinmiron** [GrafiteInc/CMS#134]
![screenshot-2018-4-17 grafite cms images](https://user-images.githubusercontent.com/9200637/38871446-93036d76-4259-11e8-9dcd-112087b94218.png)

When I click on the image I see:

![screenshot-2018-4-17 grafite cms images edit](https://user-images.githubusercontent.com/9200637/38871510-c32c7628-4259-11e8-8ad6-f51cf06ee6e2.png)

I try to change the image:
![screenshot-2018-4-17 laravel error](https://user-images.githubusercontent.com/9200637/38871638-174b9f72-425a-11e8-8385-ed789159e8b7.png)

**Comment by mlantz** [comment]
Hey @alinmiron that may be a bug from the recent release, I'll look into fixing it today, thanks

**Comment by mlantz** [comment]
This should be resolved in the latest version
