### ISSUE TITLE
Feature Request: DataTables Integration

### ISSUE THREAD

**Issue by elanclarkson** [GrafiteInc/CMS#137]
A requirement in my current project is to enhance all tables with sorting/filtering functionality.

I am looking to integrate the DataTables library (https://datatables.net/), perhaps with the help of this package: https://github.com/yajra/laravel-datatables

Would a PR be accepted for such a feature?

**Comment by elanclarkson** [comment]
Update: Ahh sorry! I somehow missed that sorting and searching is already built in, so I'm guessing you wouldn't be open to a PR of this nature.

Feel free to close this... :)

**Comment by mlantz** [comment]
I really appreciate the idea and desire to contribute, but at this moment doing that would require massive changes to the admin flow. You can implement it in your own instance by modifying the published cms view files. That being said, I am working on a unified search bar which will likely be in the next release sometime in June.
