### ISSUE TITLE
Composer requires YABhq/LaraTest.git

### ISSUE THREAD

**Issue by rjadr** [GrafiteInc/CMS#138]
I'm getting a RuntimeException when installing Grafite with composer:

`Failed to clone https://github.com/YABhq/LaraTest.git via https, ssh protocols, aborting.` 

This particular repository seems to have been removed from github.

**Comment by mlantz** [comment]
What version are you currently using?

**Comment by rjadr** [comment]
Ah, it's trying to install version 2.3, probably because the hosting provider runs php 5.6.36. Thanks!
