### ISSUE TITLE
Routes not working after simple installation

### ISSUE THREAD

**Issue by TheDutchDev** [GrafiteInc/CMS#139]
Hi,

I've been trying to get this CMS working in a default laravel application, but the I cant seem to get the routes to work.

I've followed the steps on the getting started page(https://docs.grafite.ca/cms/) and the steps in the console(npm install, dev run and adding the import to scss file). 

I've reinstalled both laravel and Grafite 4 times now but it just doesnt work. I also tried installing it via the complex setup, which broke even more things..

When I go to the website, the homepage seems to be working fine, but as soon as I click on Login or any other tab, it takes me to the "AAH" "Where am I?" page.

How do I solve this?

Thanks!

- Niels

**Comment by mlantz** [comment]
Please provide your `AppRoutesProvider.php`

**Comment by TheDutchDev** [comment]
I'm assuming you mean the `App\Providers\RouteServiceProvider.php`?

`namespace App\Providers;

use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;

class RouteServiceProvider extends ServiceProvider
{
    /**
     * This namespace is applied to your controller routes.
     *
     * In addition, it is set as the URL generator's root namespace.
     *
     * @var string
     */
    protected $namespace = 'App\Http\Controllers';

    /**
     * Define your route model bindings, pattern filters, etc.
     *
     * @return void
     */
    public function boot()
    {
        //

        parent::boot();
    }

    /**
     * Define the routes for the application.
     *
     * @return void
     */
    public function map()
    {
        $this->mapApiRoutes();

        $this->mapWebRoutes();

        //
    }

    /**
     * Define the "web" routes for the application.
     *
     * These routes all receive session state, CSRF protection, etc.
     *
     * @return void
     */
    protected function mapWebRoutes()
    {
        Route::middleware('web')
             ->namespace($this->namespace)
             ->group(function() { 
			require base_path('routes/web.php');
			require base_path('routes/cms.php'); });
    }

    /**
     * Define the "api" routes for the application.
     *
     * These routes are typically stateless.
     *
     * @return void
     */
    protected function mapApiRoutes()
    {
        Route::prefix('api')
             ->middleware('api')
             ->namespace($this->namespace)
             ->group(base_path('routes/api.php'));
    }
}
`

**Comment by mlantz** [comment]
Yeah sorry, I suspect the `cms.php` routes file is the standard, what does your `web.php` routes file look like, did you alter anything outside of the simple setup? Or is the issue happening right after you run the `php artisan grafite:cms` command?

**Comment by TheDutchDev** [comment]
Yeah it happens right after a fresh installation.

I'm running it on XAMPP and laravel 5.6

**Comment by mlantz** [comment]
I'll have to try some fresh builds tonight to see if I can replicate it.

**Comment by sleepless** [comment]
Had the same problem and solved it. Thought to open an issue and saw that there already is one. Well, this is the problem and solution: https://stackoverflow.com/questions/51227231/laravel-reflectionexception-class-does-not-exist/51227377#51227377 (at least for complex setup)

I'd fix it but this has cost me enough time already. I have to move on with the project.

**Comment by mlantz** [comment]
After reading through the comments on StackOverflow, I'll make some adjustments to help improve this, thanks @sleepless
