### ISSUE TITLE
artisan module:crud abc fails with unknown error 

### ISSUE THREAD

**Issue by heingithub** [GrafiteInc/CMS#140]
A clean new CMS install fails when attempting to create/generate a new module. Unable to determine the reason for the failure, log and command below -

...
php artisan module:crud abc
Building the admin side...
Building controller...
Building model...
Building request...
Building service...

   Exception  : Unable to generate your Module

  at /var/www/html/udder01/vendor/grafite/cms/src/Console/ModuleCrud.php:152
    148|             $this->line('');
    149|             $this->info('Add this to your `app/Providers/RouteServiceProver.php` in the `mapWebRoutes` method:');
    150|             $this->comment("\nrequire base_path('routes/".$config['_lower_casePlural_']."-web.php');\n");
    151|         } catch (Exception $e) {
  > 152|             throw new Exception('Unable to generate your Module', 1);
    153|         }
    154| 
    155|         Artisan::call('make:migration', [
    156|             'name' => 'create_'.str_plural(strtolower($this->table)).'_table',

  Exception trace:

  1   Grafite\Cms\Console\ModuleCrud::handle()
      /var/www/html/udder01/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

  2   call_user_func_array([])
      /var/www/html/udder01/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

  Please use the argument -v to see more details.
...

**Comment by heingithub** [comment]
Output with --vvvv

...
php artisan module:crud -vvv abc
Building the admin side...
Building controller...
Building model...
Building request...
Building service...

   Exception  : Unable to generate your Module

  at /var/www/html/udder01/vendor/grafite/cms/src/Console/ModuleCrud.php:152
    148|             $this->line('');
    149|             $this->info('Add this to your `app/Providers/RouteServiceProver.php` in the `mapWebRoutes` method:');
    150|             $this->comment("\nrequire base_path('routes/".$config['_lower_casePlural_']."-web.php');\n");
    151|         } catch (Exception $e) {
  > 152|             throw new Exception('Unable to generate your Module', 1);
    153|         }
    154| 
    155|         Artisan::call('make:migration', [
    156|             'name' => 'create_'.str_plural(strtolower($this->table)).'_table',

  Exception trace:

  1   Grafite\Cms\Console\ModuleCrud::handle()
      /var/www/html/udder01/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

  2   call_user_func_array([])
      /var/www/html/udder01/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

  3   Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /var/www/html/udder01/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87

  4   Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      /var/www/html/udder01/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31

  5   Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      /var/www/html/udder01/vendor/laravel/framework/src/Illuminate/Container/Container.php:564

  6   Illuminate\Container\Container::call()
      /var/www/html/udder01/vendor/laravel/framework/src/Illuminate/Console/Command.php:183

  7   Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /var/www/html/udder01/vendor/symfony/console/Command/Command.php:251

  8   Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /var/www/html/udder01/vendor/laravel/framework/src/Illuminate/Console/Command.php:170

  9   Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/html/udder01/vendor/symfony/console/Application.php:886

  10  Symfony\Component\Console\Application::doRunCommand(Object(Grafite\Cms\Console\ModuleCrud), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/html/udder01/vendor/symfony/console/Application.php:262

  11  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/html/udder01/vendor/symfony/console/Application.php:145

  12  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/html/udder01/vendor/laravel/framework/src/Illuminate/Console/Application.php:89

  13  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/html/udder01/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122

  14  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/html/udder01/artisan:37

...

**Comment by JordinMarshall** [comment]
I’m experiencing this blocking issue as well

**Comment by mlantz** [comment]
I found the core issue today - will be pushing fix in the next day or two. Thank you for your patience.

**Comment by heingithub** [comment]
Thank you @mlantz , one of the issues is the fact that the ".txt" templates referred to in the module generator do not exist. I have been able to get past the error by copying the templates over to the correct directory.

I have not tested the resulting code though.

**Comment by mlantz** [comment]
Yeah thats the main issue, but I've also updated the CrudMaker itself to create the stub files if they dont exist so it should prevent this from happening again should the stubs change :)

**Comment by mlantz** [comment]
Should be corrected in the recent release
