### ISSUE TITLE
failed instalation L 5.5 

### ISSUE THREAD

**Issue by amine8ghandi8amine** [GrafiteInc/CMS#141]
- Installing yab/laratest (v0.1.1): Downloading (0%)    Failed to download yab/laratest from dist: The "https://codeload.github.com/YABhq/LaraTest/legacy.zip/1223d52aeb526ac16dabda7aa3523b0f81865468" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing yab/laratest (v0.1.1): Cloning 1223d52aeb from cache
    1223d52aeb526ac16dabda7aa3523b0f81865468 is gone (history was rewritten?)

                                                                               
  [RuntimeException]                                                           
  Failed to execute git checkout '1223d52aeb526ac16dabda7aa3523b0f81865468' -  
  - && git reset --hard '1223d52aeb526ac16dabda7aa3523b0f81865468' --          
                                                                               
  fatal: reference is not a tree: 1223d52aeb526ac16dabda7aa3523b0f81865468

**Comment by mlantz** [comment]
We're only able to support 5.6 and up at this point due to package name transitions.
