### ISSUE TITLE
backend-theme: dark style issues

### ISSUE THREAD

**Issue by Rihoj** [GrafiteInc/CMS#143]
So I set my backend-theme to dark and the input boxes just don't play well with that style.

1. The input boxes and textareas have a black background and on focus the text goes to gray. This makes it hard to read.
2. The redactor editor does not play well with headers when in the dark theme. Headers are still colored black which makes it impossible to see due to the black background color.

**Comment by mlantz** [comment]
These should be resolved in the latest release last night

**Comment by Rihoj** [comment]
This looks a lot better. Thank you so much for the quick work!
