### ISSUE TITLE
cmsNotify function not clearing class

### ISSUE THREAD

**Issue by Rihoj** [GrafiteInc/CMS#144]
I am using the cmsNotify function in my own method and if you click on the x or let the message fade on it's own the class that it was given does not get removed from the code.

```
axios.patch($(this).attr('action'), $(this).serialize())
    .then((response) => {
        cmsNotify("Property Saved Correctly", "alert-success");
    })
    .catch((error) => {
        cmsNotify("There was an error", "alert-danger");
    });
});
```

After calling the success and then the danger I get the following:
```
<div class="cms-notification alert-success alert-danger" style="display: none; right: -300px;">
    <div class="cms-notify">
        <p class="cms-notify-comment"></p>
    </div>
    <div class="cms-notify-closer">
        <span class="fa fa-times cms-notify-closer-icon"></span>
    </div>
</div>
```

This also causes the danger style to be perfered, so when I call danger and then success the messasge is still red with the following the the dom:
```
<div class="cms-notification alert-danger alert-success" style="display: none; right: -300px;">
    <div class="cms-notify">
        <p class="cms-notify-comment"></p>
    </div>
    <div class="cms-notify-closer">
        <span class="fa fa-times cms-notify-closer-icon"></span>
    </div>
</div>
```

Would you please have the cmsNotify function clear the styling that was placed on this? Please keep in mind when a user click the button before the alert has cleared as well.

Thank you.

**Comment by Rihoj** [comment]
I created a pull request for this. I figured instead of just asking for changes I could contribute a little bit as well. #145

**Comment by mlantz** [comment]
Looked good, I'll push a version update tomorrow
