### ISSUE TITLE
Missing attributes in formmaker

### ISSUE THREAD

**Issue by mnwalker** [GrafiteInc/CMS#146]
My install was an upgrade from quarx so not sure if part of the factor, but I did a full reinstall and rebuilt database and one issue persists.

> laravel.ERROR: array_keys() expects parameter 1 to be array, null given (View: /var/www/html/resources/views/vendor/cms/modules/pages/edit.blade.php) {"userId":1,"email":"admin@example.com","exception":"[object] (ErrorException(code: 0): array_keys() expects parameter 1 to be array, null given (View: /var/www/html/resources/views/vendor/cms/modules/pages/edit.blade.php) at /var/www/html/vendor/grafite/formmaker/src/Services/FormMaker.php:205, ErrorException(code: 0): array_keys() expects parameter 1 to be array, null given at /var/www/html/vendor/grafite/formmaker/src/Services/FormMaker.php:205)

My fix which works
```
vendor/grafite/formmaker/src/Services/FormMaker.php
Line 205
$columns = is_array($object['attributes']) ? array_keys($object['attributes']) : [];
```

**Comment by mlantz** [comment]
Thanks, I'll put in a fix, its likely cause its not reading the config file anymore, which is causing a null response in the FormMaker or potentially thats the problem.
