### ISSUE TITLE
Error:   mkdir(): No such file or directory

### ISSUE THREAD

**Issue by ujackson** [GrafiteInc/CMS#15]
When you run php artisan vendor:publish --provider="Yab\Quarx\QuarxProvider"

It gives you this error:

  [ErrorException]
  mkdir(): No such file or directory

**Comment by ujackson** [comment]
The error was from line:22 on vendor/yab/laracogs/src/LaracogsProvider.php

I had to manually create the folders to make it work: resources/laracogs/crud

**Comment by mlantz** [comment]
Thanks for catching that, I'll get the fix into Laracogs ASAP :) Just do a composer update in like 30 min.
