### ISSUE TITLE
Net module menu has incorrect styling

### ISSUE THREAD

**Issue by REPTILEHAUS** [GrafiteInc/CMS#151]
1) the menu navigation link is un-styled compared to the other links

2) when you create a new module using camelCase naming convention it breaks giving error
No hint path defined for [doesntWork].

**Comment by mlantz** [comment]
I just tested `artisan module:crud SchoolClass` and `artisan module:crud schoolTeachers` and both worked fine using the latest versions of the packages. 

The styling is missing, I'll add that fix this weekend.

**Comment by REPTILEHAUS** [comment]
@mlantz will the styling be fixed soon do you know

**Comment by mlantz** [comment]
Hey @REPTILEHAUS sorry for the lateness of all this, I've been crazy busy building a new product which will be released in the next couple weeks. I have numerous updates for the CMS I'll be pushing as well.

**Comment by mlantz** [comment]
Corrected in the latest release
