### ISSUE TITLE
Multi-site based on Grafite CMS

### ISSUE THREAD

**Issue by datnguyen293** [GrafiteInc/CMS#153]
Hi, I want to build domain based multi-site on top of Grafite CMS but I don't know where to start the customization. Can you please give me some ideas?

Thanks and best regards,
Dat

**Comment by mlantz** [comment]
Funny you should ask that, its currently in my plans for a future release to support that. At this exact moment, I don't have any real strategies to share.

**Comment by datnguyen293** [comment]
Thank you for your reply. I'm looking forward for the future release :)
