### ISSUE TITLE
Accessing menu when not logged in as Admin

### ISSUE THREAD

**Issue by ryk248** [GrafiteInc/CMS#154]
Hi,

I have created a CMS menu and am trying to access it on the home page when I am not logged in as Admin. Unfortunately, I have found no luck and have been unable to access it. 

Is there anyway this could be possible?

Thanks!

**Comment by mlantz** [comment]
Thats really hard for me to make a proper assessment on. Can you please provide an example?

**Comment by ryk248** [comment]
I am not sure if I will be able to give a live working example, but, I can try explaining it in depth. 
I have created a menu with a couple of links and converted it into a navigation bar. Although, I can see the menu only if I am logged into the CMS as an admin user. 
If i don't login and go to the landing page (which I have changed to my home page and which is using the menu), I am unable to view the menu that I have created.

I hope this helps!

**Comment by mlantz** [comment]
Updated and corrected in the latest release
