### ISSUE TITLE
Can not create menu

### ISSUE THREAD

**Issue by RushabhJoshi** [GrafiteInc/CMS#156]
On menu create a page I inserted name and slug called Top and top respectively
and its shows an error like 

Undefined variable: menu

```php
// error occurs after this line of store method in menucontroller
$this->repository->store($request->all())
```

**Comment by mlantz** [comment]
Please provide the version of both the CMS and Laravel that you're using.

**Comment by RushabhJoshi** [comment]
laravel/framework=v5.6.28
grafite/builder=v2.4.1
grafite/cms=v3.1.5
grafite/crudmaker=v1.4.3
grafite/crypto=v1.1.0
grafite/formmaker=v1.3.3

**Comment by mlantz** [comment]
There has been a new release please let me know if this is still an issue
