### ISSUE TITLE
Can not create blog and page

### ISSUE THREAD

**Issue by RushabhJoshi** [GrafiteInc/CMS#157]
Whenever I tried to create a blog or page it will show the same error like below

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column '_url' in 'field list' (SQL: insert into `pages` (`title`, `url`, `entry`, `seo_description`, `seo_keywords`, `is_published`, `published_at`, `_url`, `blocks`, `updated_at`, `created_at`) values (Home, home, <p>Home page<br></p>, , , 1, 2018-07-24 11:44:00, /cms/pages, {}, 2018-07-24 11:44:44, 2018-07-24 11:44:44))
```

**Comment by mlantz** [comment]
Please provide the CMS version and Laravel version that youre using. Also, have you altered the JS or published config files?

**Comment by RushabhJoshi** [comment]
laravel/framework=v5.6.28
grafite/builder=v2.4.1
grafite/cms=v3.1.5
grafite/crudmaker=v1.4.3
grafite/crypto=v1.1.0
grafite/formmaker=v1.3.3

**Comment by mlantz** [comment]
There has been a new release please let me know if this is still an issue
