### ISSUE TITLE
/cms/dashboard says unauthorized

### ISSUE THREAD

**Issue by rextech03** [GrafiteInc/CMS#158]
what can I do I used the complex method I use my normal admin details to log in as i changed from cms to admin in route config but no difference. also when I use the crud maker the index and show page does not work.

**Comment by mlantz** [comment]
These are two separate issues, the first one, regarding the routing, what is the actual issue? Do the routes not work? Did you add the correct parts to the RouteServiceProvider?

Second, did the crud maker output any errors? Are you getting errors when you try to view those routes (index and show)?

**Comment by rextech03** [comment]
I am get the error "unauthorised" when I try to view the index and show
route

**Comment by mlantz** [comment]
I'm unable to replicate any of this. I'll need you to provide more details that match the bug reporting guidelines. The complex setup assumes that you have your own auth. Please read the follow docs regarding [CMS access](https://docs.grafite.ca/cms/#cms-access)
