### ISSUE TITLE
Redactor does not allow you to format bold, italic, underline, sup, sub etc. for selected text

### ISSUE THREAD

**Issue by shabaz-ejaz** [GrafiteInc/CMS#159]
**Describe the bug**
Redactor does not allow you to format bold, italic, underline, sup, sub etc. for selected text

**To Reproduce**
1. Go to pages
2. Click on create new page
3. Scroll down to the content WYSIWYG
4. Try and select an individual work and format in bold / italic.

**Expected behavior**
The selected piece of text should be formatted.

**Screenshots**

![2018-08-30_09h17_47](https://user-images.githubusercontent.com/29374282/44839036-a7027380-ac35-11e8-9b5e-53f24c24f64c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser: Chrome 
 - Version 68.0.3440.106

**Additional context**
This is related to the following issue: https://github.com/vova07/yii2-imperavi-widget/issues/89

**Comment by mlantz** [comment]
Yeah I've recently started the update for Redactor 3, I should have it done by this weekend

**Comment by shabaz-ejaz** [comment]
Any updates on this?

**Comment by mlantz** [comment]
Updated in the latest release

**Comment by shabaz-ejaz** [comment]
Why is this closed? Just updated to the latest release (v3.1.7) and I can confirm the issue still remains:

![2018-09-04_09h17_56](https://user-images.githubusercontent.com/29374282/45019134-7c446080-b023-11e8-9151-cdb3ca0eb2eb.png)

**Comment by mlantz** [comment]
Please clear your caches etc and make sure the new version of Redactor loads. The entire toolbar of the editor looks different now.

**Comment by shabaz-ejaz** [comment]
I've cleared all the cache, cleared composer cache, compiled the assets again and restarted the server. Still no change.

**Comment by shabaz-ejaz** [comment]
Okay so after running `npm run production` and clearing the cache again this issue seems to be fixed now. Thanks
