### ISSUE TITLE
Cannot upload files / image - "The location field is required"

### ISSUE THREAD

**Issue by shabaz-ejaz** [GrafiteInc/CMS#160]
**Describe the bug**
I cannot add files and images through the backend of the CMS. I keep getting the error:

> The location field is required.

**To Reproduce**
1. Go to files
2. Click on add new
3. Choose an image
4. See the error

**Expected behavior**
Should upload the file / image

**Screenshots**
![2018-08-30_09h23_05](https://user-images.githubusercontent.com/29374282/44839404-98688c00-ac36-11e8-8d1d-654faecb8076.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser: Chrome 
 - Version 68.0.3440.106

**Additional context**

**Comment by mlantz** [comment]
I'll have to review on a Windows device this weekend

**Comment by shabaz-ejaz** [comment]
Any updates on this?

**Comment by mlantz** [comment]
Please update to the latest release and let me know if this is still an issue

**Comment by shabaz-ejaz** [comment]
Updated to the latest release (v3.1.7) and the issue is still there:  
![2018-09-04_09h19_44](https://user-images.githubusercontent.com/29374282/45019247-c299bf80-b023-11e8-88cc-be86d70d710c.png)

**Comment by mlantz** [comment]
Can you please provide me with the console errors or statements. I'm unable to replicate this

**Comment by shabaz-ejaz** [comment]
I get the following error that appears for a split second when I click save and then it disappears:

![2018-09-04_13h42_18](https://user-images.githubusercontent.com/29374282/45031996-6dbc7000-b048-11e8-856c-0e311cb53915.png)


Other than that there are no console errors.

**Comment by mlantz** [comment]
Hmmm, looks like an issue with the url being set to admin, it has to be set to `cms` its a fixed url since its handling the uploads. I'll look into resolving that.

**Comment by shabaz-ejaz** [comment]
Yeah the cms config allows you to change the backend prefix, so I'm guessing it's pulling from that.

**Comment by mlantz** [comment]
I'm pushing the fix this evening, you will have to get the latest cms vendor view files if your app has published these to the `resources\vendor\cms` directory

**Comment by shabaz-ejaz** [comment]
Thanks. Seems to be working fine after updating and publishing the vendor files.

**Comment by joshjabs** [comment]
I'm still getting this error in v3.2.2 but my console displays a 500 error instead of the  405:
![image](https://user-images.githubusercontent.com/6274678/49236247-ee290d80-f3b8-11e8-8453-09b358f77b3a.png)
