### ISSUE TITLE
Make Crud: New template is different than installed templates

### ISSUE THREAD

**Issue by yapsr** [GrafiteInc/CMS#161]
**Describe the bug**
When running a make:crud command, the newly created CRUD pages in the cms admin dashboard look and behave differently than the pages that come with the initial installed modules of the CMS (i.e. blog).

![image](https://user-images.githubusercontent.com/3018553/44894478-33716c80-acf0-11e8-94cd-619268f1bf23.png)

**To Reproduce**
1. `php artisan crud:make tablename`
2.  browse and log in to cms admin dashboard `http://domain.ltd/cms/tablename`

**Expected behavior**
I would expect the newly created module to be behaving exactly similar to the alreay existing modules:

![image](https://user-images.githubusercontent.com/3018553/44894563-a4188900-acf0-11e8-8384-5bd33a84ab3d.png)

**Additional context**
It seems that templates used for this console command in `vendor/grafite/cms/src/Templates/CRUD/Views/*.txt` are different from the templates used in the core modules in `vendor/grafite/cms/src/Views/*.blade.php`

It also seems that these templates are different from the templates used for the separate package `grafite/crudmaker`.

This is also the case for the generated (or missing) service, cms backend controller, frontend controller, facade etc. It looks like the templates are some versions behind compared to the core modules.

It would be really nice (and less confusing) if all these templates are the same.

**Versions**
grafite/cms 3.1.6
grafite/crudmaker 1.4.3

**Comment by mlantz** [comment]
The templates should certainly look mostly the same, I'll need to review that, that screen above doesn't look right at all

**Comment by mlantz** [comment]
Updated and corrected in the latest release

**Comment by yapsr** [comment]
@mlantz Thank you!
