### ISSUE TITLE
Config cms.module-directory is case sensitive

### ISSUE THREAD

**Issue by yapsr** [GrafiteInc/CMS#162]
**Describe the bug**
With cms modules and running `composer dump`, the module providers inside that directory are not found.

**To Reproduce**
1. `php artisan make:crud name` on case sensitive platform, like Linux.
2. `composer dump`

**Solution**
1. Rename the directory cms/modules to cms/Modules
2. Set `cms.module-directory` in `config/cms.php`  to `'cms/Modules'`

**Comment by mlantz** [comment]
Will fix and push in the next couple days - lots of updates are on their way!

**Comment by mlantz** [comment]
Corrected in the latest release

**Comment by yapsr** [comment]
@mlantz Great!
