### ISSUE TITLE
After initial install, there are no routes or set up fro the admin section. 

### ISSUE THREAD

**Issue by tech911Admin** [GrafiteInc/CMS#163]
Clicking on the link displays page not found and looking at the routes in cms does not find any addresses for .../admin or .../admin/dashboard or ../admin/users. I also do not see a section for this area set up in the blade files. What did I miss?

**Comment by tech911Admin** [comment]
Clicking on the link displays page not found and looking at the routes in cms does not find any addresses for .../admin or .../admin/dashboard or ../admin/users. I also do not see a section for this area set up in the blade files. What did I miss?

**Comment by mlantz** [comment]
Please follow the guidelines when submitting issues they are intended to help me determine the root of your issue. 

Based on your descriptions I cannot determine what you 'missed'. If you used the `simple` setup then the setup process should have worked correctly. If you used the complex setup then there may have been multiple steps you missed. The Admin components are ONLY available through the simple setup. If your application does not have those routes already then you can remove those links from the admin panel by publishing the vendor files to your `resources/views/vendor` directory
