### ISSUE TITLE
Where do the published pages go?

### ISSUE THREAD

**Issue by tech911Admin** [GrafiteInc/CMS#164]
Sorry for another stupid question, I entered a url of 'test-page' for my first page but it does not show up at <url>/test-page. 

Have you guys published a wiki or any docs for this other than the basic install?

Thanks -

**Comment by tech911Admin** [comment]
It appears the published pages go to <url>/page/test-page

.... but when I go there I receive this error -

But when I go there, there is no pages controller set up:

Class Cms\PagesController does not exist

I see the pages controller installed in the controllers\cms directory, but for some reason routes have not been set up for it correctly. I don't want to keep jury rigging this thing. I might have missed a step during install. Can someone please tell me what I missed.

**Comment by mlantz** [comment]
You will need to confirm that in your `RouteServiceProvider.php` your `mapWebRoutes` method looks similar to:

```
Route::middleware('web')
    ->namespace($this->namespace)
    ->group(function () {
        require base_path('routes/web.php');
        require base_path('routes/cms.php');
    });
```

In order to get wildcard urls to work correctly you have to add a special route to to the CMS routes file, as mentioned in the [docs](https://docs.grafite.ca/cms).
