### ISSUE TITLE
Cannot Upload Image

### ISSUE THREAD

**Issue by sbasu** [GrafiteInc/CMS#166]
Hi, 
cannot upload image using Images section, I am using WIN 10, Chrome browser. I also updated to the latest release but no luck. Also I cannot delete the image from Generic Delete button.

![delete_button_not_working](https://user-images.githubusercontent.com/1073727/45029873-b3d4fc00-b067-11e8-8789-8fd2f3328ed3.png)
![no_image_upload](https://user-images.githubusercontent.com/1073727/45029879-b899b000-b067-11e8-8811-c3d947ed7409.png)

**Comment by mlantz** [comment]
You need to make sure you symlink your storage on your server setup https://laravel.com/docs/5.7/filesystem#configuration
