### ISSUE TITLE
MySQL specific query on Blade template, it will fail with other DB engine

### ISSUE THREAD

**Issue by brBart** [GrafiteInc/CMS#170]
**Describe the bug**
This is a MySQL specific query on Blade template, it will fail with other DB engine
https://github.com/GrafiteInc/CMS/blob/9168bda38b853ada2084167194354793e00eeceb/src/PublishedAssets/Setup/resources/views/admin/dashboard.blade.php#L121

**To Reproduce**
use any other DB e.g. SQLite on unit tests

**Comment by mlantz** [comment]
The requirements for the Grafite CMS do require MySQL 5.7+ we don't actively support any other databases
