### ISSUE TITLE
Error installation: simple setup not working...

### ISSUE THREAD

**Issue by OMSmolina** [GrafiteInc/CMS#171]
**Describe the bug**
Simple setup not working..

`"Class cms-language does not exist"`

**To Reproduce**
1: Install laravel 5.7.*
2: composer require grafite/cms (^3.2)
3: php artisan vendor:publish --provider="Grafite\Cms\GrafiteCmsProvider"
4: php artisan grafite:cms-setup
4.1: Please confirm that you have a database set and configured in your .env file. ( yes/no) [no]: yes

**Screenshots**
![image](https://user-images.githubusercontent.com/6513086/45492235-12872d80-b76c-11e8-86d7-dec48acd1319.png)

**Comment by Perafan18** [comment]
@oscarmolinadev Is really confusing but you must continue with the complex setup, add to the Kernel Route Middleware

```
        'admin' => \App\Http\Middleware\Admin::class,
        'cms' => \App\Http\Middleware\GrafiteCms::class,
        'cms-api' => \App\Http\Middleware\GrafiteCmsApi::class,
        'cms-language' => \App\Http\Middleware\GrafiteCmsLanguage::class,
        'cms-analytics' => \Grafite\Cms\Middleware\GrafiteCmsAnalytics::class,
```

**Comment by mlantz** [comment]
There must be something broken in the setup if its not adding the middleware to the Kernel automatically - I'll look at this

**Comment by mlantz** [comment]
Should be resolved now in the latest build
