### ISSUE TITLE
use route instead of url...

### ISSUE THREAD

**Issue by khyoz** [GrafiteInc/CMS#177]
**Describe the bug**
with my template, when I access a blog and blog detail I have an url like : myproject/blog/detail : this is normal
and then when I try to access another menu from this page... with url=contact
I have a wrong page displayed : myproject/blog/contact instead of myproject/contact
If I add a name in the route definition, and link my href="route('contact')" 
then I have no problem, even when I'm in the blog detail page
So when I check the cms code, all the routes refer to URL
I think it's better to change all of that to route, and add a name to each route in cms.php

**Comment by mlantz** [comment]
I understand the value of setting everything as routes, but you **bug** confuses me. Is there a menu link you are generating that is not linking correctly? Are you adding in your own code links and not properly setting the url? Are you having issues with the admin side of the code or on the portions of code which are published to your application? The code published to your application can be modified as you see fit. Please provide more specific examples and where these link issues are happening

**Comment by khyoz** [comment]
sorry, I changed already every link with the route name already once I discovered that, and have no problems. I did nothing particular, I just discovered that while I was browsing through my links from menu and pages, then I have seen that you used URL and not Route...I tried with route and everything was ok, and just wanted to warn you. Of course if I can reproduce I will let you know, as I will use GrafiteCMS for several internal projects...in fact already started....I'm starting to like GrafiteCMS...excepted for static pages....but I'm sure it will be improved in the future !
