### ISSUE TITLE
Postgresql 

### ISSUE THREAD

**Issue by jordyvanvijfeijken** [GrafiteInc/CMS#183]
We're using Postgres for our database. I installed Grafite and everything went well, but when I go to the admin dashboard, I get this error.

```SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "LIKE" LINE 1: SHOW VARIABLES LIKE "%version%"; ^ (SQL: SHOW VARIABLES LIKE "%version%";) (View: /var/www/php/sites/kringloop-grafite/resources/views/admin/dashboard.blade.php)```

For Postgress it should be like this:

```  
@foreach (DB::select('SELECT version();') as $dbVar)
                <tr>
                    <td>Version</td>
                    <td>{{$dbVar->version}}</td>
               </tr>
@endforeach
```

**Comment by mlantz** [comment]
We don't actively support Postgres, feel free to remove that and things should work fine. This issue has been reported once before, thanks.
