### ISSUE TITLE
Having difficulty installing and using with Laravel Spark.

### ISSUE THREAD

**Issue by adambant** [GrafiteInc/CMS#19]
I was able to install Quarx on a new installation of Laravel Spark, but when I ran the "php artisan quark:setup" command I got conflicts of duplicate database table names that conflict with the Laravel Spark such as "teams". I am attempting to namespace all the new Quarx tables with "quarx_" to differentiate the new tables with the Spark ones. All tables will be different except they will share the "users" table. I am not sure how successful I will be in getting it all to work together.

**Comment by mlantz** [comment]
Yeah I'm skeptical that Quarx and Spark would work well together. Quarx works perfectly with Laracogs though which gives you similar components as Spark, but also has a great CRUD builder :)

**Comment by mlantz** [comment]
If you get them to play nicely together I'd love to see how you do it. It would be a great 'how to' to add to the website. Thanks.

**Comment by adambant** [comment]
Will report back my success/failure when I get there :-)
