### ISSUE TITLE
LogicException  : Key path does not exist or is not readable

### ISSUE THREAD

**Issue by karneaud** [GrafiteInc/CMS#191]
**Describe the bug**
When trying to run the command `php artisan route:list` I get the subject error

**To Reproduce**
1. install laravel
2. run `php artisan grafite:cms-setup`
3. run `php artisan route:list`

**Expected behavior**
Should get a list of routes

**Desktop (please complete the following information):**
 - OS: Docker Linux

**Additional context**
Full Error

> LogicException  : Key path "file:///var/www/html/storage/oauth-private.key" does not exist or is not readable
> 
>   at /var/www/html/vendor/league/oauth2-server/src/CryptKey.php:45
>     41|             $keyPath = 'file://' . $keyPath;
>     42|         }
>     43|
>     44|         if (!file_exists($keyPath) || !is_readable($keyPath)) {
>   > 45|             throw new \LogicException(sprintf('Key path "%s" does not exist or is not readable', $keyPath));
>     46|         }
>     47|
>     48|         if ($keyPermissionsCheck === true) {
>     49|             // Verify the permissions of the key
> 
>   Exception trace:
> 
>   1   League\OAuth2\Server\CryptKey::__construct("file:///var/www/html/storage/oauth-private.key")
>       /var/www/html/vendor/laravel/passport/src/PassportServiceProvider.php:234
> 
>   2   Laravel\Passport\PassportServiceProvider::makeCryptKey("oauth-private.key")
>       /var/www/html/vendor/laravel/passport/src/PassportServiceProvider.php:203
> 
>   Please use the argument -v to see more details.

**Comment by mlantz** [comment]
The cms-setup will only work on an a fresh Laravel application it will not likely work if its being added to an existing app. `PassportServiceProvider` is not a default portion of the Laravel framework.
