### ISSUE TITLE
the quarx:setup hangs on 'Generating autoload files' without terminating

### ISSUE THREAD

**Issue by swanand09** [GrafiteInc/CMS#20]
Hello, 
When I run 'php artisan quarx:setup', I am stuck on 'Generating autoload files' without exiting. Can anybody please clarify about this? Is there an alternative to get install Quarx?
 My OS is ubuntu 16.04

Thanks

**Comment by miloszwatroba** [comment]
I'm having the same problem on OSX El Capitan

**Comment by mlantz** [comment]
Turns out it was an issue with the default theme populating. The issue has been addressed. Thanks for posting the issue :)
