### ISSUE TITLE
Unable to reach demo site

### ISSUE THREAD

**Issue by Kreshnik** [GrafiteInc/CMS#24]
I am receiving an error when going to the demo site;
<img width="950" alt="screen shot 2016-10-23 at 7 34 09 pm" src="https://cloud.githubusercontent.com/assets/1788349/19628158/c13ac858-9957-11e6-9324-a682fd855775.png">

**Comment by mlantz** [comment]
Odd, seems fine now, thanks for letting me know.

**Comment by samundra** [comment]
It's working fine for me as well. Try to clear the cache and give it retry.

**Comment by boynet** [comment]
still not working get laravel error

```
ErrorException in QuarxService.php line 270:
Trying to get property of non-object (View: /home/admin/web/demo.quarx.info/public_html/resources/themes/demo/partials/navigation.blade.php) (View: /home/admin/web/demo.quarx.info/public_html/resources/themes/demo/partials/navigation.blade.php) (View: /home/admin/web/demo.quarx.info/public_html/resources/themes/demo/partials/navigation.blade.php)
```

**Comment by mlantz** [comment]
fixed it this morning. The demo is reset automatically every 2 hours
