### ISSUE TITLE
[ReflectionException] Class Yab\Quarx\Models\ does not exist

### ISSUE THREAD

**Issue by chimenk** [GrafiteInc/CMS#27]
I'm doing Quarx installation with simple setup. Everything works fine, both frontend and admin panel working. But, when i trying to list routes there is this error :

[2016-11-03 11:53:34] local.ERROR: ReflectionException: Class Yab\Quarx\Models\ does not exist in /opt/www/linc/vendor/laravel/framework/src/Illuminate/Container/Container.php:749
Stack trace:
#0 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): ReflectionClass->__construct('Yab\\Quarx\\Model...')
#1 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Container/Container.php(644): Illuminate\Container\Container->build('Yab\\Quarx\\Model...', Array)
#2 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make('Yab\\Quarx\\Model...', Array)
#3 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(106): Illuminate\Foundation\Application->make('Yab\\Quarx\\Model...', Array)
#4 /opt/www/linc/vendor/yab/quarx/src/Controllers/ApiController.php(17): app('Yab\\Quarx\\Model...')
#5 [internal function]: Yab\Quarx\Controllers\ApiController->__construct(Object(Illuminate\Http\Request))
#6 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Container/Container.php(794): ReflectionClass->newInstanceArgs(Array)
#7 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Container/Container.php(644): Illuminate\Container\Container->build('Yab\\Quarx\\Contr...', Array)
#8 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make('Yab\\Quarx\\Contr...', Array)
#9 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Foundation\Application->make('Yab\\Quarx\\Contr...')
#10 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Routing/Route.php(316): Illuminate\Routing\Route->getController()
#11 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Routing/Route.php(278): Illuminate\Routing\Route->controllerMiddleware()
#12 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(141): Illuminate\Routing\Route->gatherMiddleware()
#13 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(118): Illuminate\Foundation\Console\RouteListCommand->getMiddleware(Object(Illuminate\Routing\Route))
#14 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(88): Illuminate\Foundation\Console\RouteListCommand->getRouteInformation(Object(Illuminate\Routing\Route))
#15 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(75): Illuminate\Foundation\Console\RouteListCommand->getRoutes()
#16 [internal function]: Illuminate\Foundation\Console\RouteListCommand->fire()
#17 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#18 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#19 /opt/www/linc/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /opt/www/linc/vendor/symfony/console/Application.php(820): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /opt/www/linc/vendor/symfony/console/Application.php(187): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\RouteListCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /opt/www/linc/vendor/symfony/console/Application.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /opt/www/linc/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /opt/www/linc/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 {main}  

Will this affecting my installation?

Thank you

**Comment by mlantz** [comment]
Hey so thats an interesting one, take a look at the `routes/web.php` file and see if there is stuff defining routes for teams, try deleting that and see if still works the routes will look like:

```Route::get('team/{name}', 'TeamController@showByName');
Route::resource('teams', 'TeamController', ['except' => ['show']]);
Route::post('teams/search', 'TeamController@search');
Route::post('teams/{id}/invite', 'TeamController@inviteMember');
Route::get('teams/{id}/remove/{userId}', 'TeamController@removeMember');```

If they were in there its a leftover from the setup, I'll implement a fix and it should not affect your installation

**Comment by mlantz** [comment]
Ok, so it turns out its a bug with the ApiController, its happening because the controller defines its model in the constructor, based on the URL. I have a fix I can implement which will resolve the matter. It wont break anything other than the listing, but I'll try and have the fix released tonight
