### ISSUE TITLE
New install: setup exception 'We were unable to generate your profile, please try again later.'

### ISSUE THREAD

**Issue by Maxximus007** [GrafiteInc/CMS#28]
Hi, running `php artisan quarx:setup` gives the above exception. After proceeding with yarn and gulp I was able to login, route to /dashboard wil give an exception too:

`ReflectionException in Container.php line 749:
Class active does not exist`

Going back to the homepage, and use the button on the bottom the /quarx/dashboard route is used, and will show the dashboard just fine. Login routing issue?

**Comment by Maxximus007** [comment]
Same ReflectionException for /user/settings, /admin/users and /admin/roles

**Comment by mlantz** [comment]
Fix coming this evening. It was caused by some updates to Laracogs

**Comment by mlantz** [comment]
In order to fix your current setup, go to your routes/web.php and look for the middleware `active` remove that. Then go to the Notifications and find `ActivateUserEmail.php` and remove the 'mail' from the channels and everything should work fine. Thanks for posting an issue @Maxximus007
