### ISSUE TITLE
Error at setup: ActivateUserEmail error

### ISSUE THREAD

**Issue by Maxximus007** [GrafiteInc/CMS#29]
Fresh install on new Laravel app: running setup gives `[ErrorException]
  Undefined variable: ActivateUserEmail`. DB is not created yet so seems to be an error in the drop email routine.

Also pls check line 254 in Setup.php.

**Comment by mlantz** [comment]
Yeah looks like I had a typo, I'm adding some tests tonight

**Comment by mlantz** [comment]
Fixed
