### ISSUE TITLE
Why erro?

### ISSUE THREAD

**Issue by WeltonLSantos** [GrafiteInc/CMS#32]
link photo https://s21.postimg.org/4tnf4ikt3/Sem_t_tulo.png

**Comment by mlantz** [comment]
Is artisan working at all?

**Comment by gregolai** [comment]
I did a fresh install of Laravel 5.3 and the fixed Quarx simple setup. Everything seems to work fine. Is your artisan file missing from the D:\laragon\www directory?

**Comment by WeltonLSantos** [comment]
please tutorial in video of installation complete?

Erro in upload arqchive and ErrorException in FormMaker.php line
