### ISSUE TITLE
Quarx use same table names like I use (files...)

### ISSUE THREAD

**Issue by vincoweb** [GrafiteInc/CMS#34]
How can i fix it? I think better way is use convention like in another CMS ( naming with quarx prefix). Example: quarx_files

**Comment by mlantz** [comment]
Good idea, I've added a db-prefix for the config now, so you could specify the 'quarx_' for all the quarx content tables ex. `quarx_pages`. When using the `setup` command though it wont prefix tables like users and user meta.

**Comment by mlantz** [comment]
Will release in the next day or so

**Comment by vincoweb** [comment]
Thank you. I am waiting
