### ISSUE TITLE
Fresh install with translations table error

### ISSUE THREAD

**Issue by chadpriddle** [GrafiteInc/CMS#35]
Fresh install of Laravel 5.3 and I get this error when loading the home page. I followed the github setup to a tee and still get this error. I look in the translations table and there is no rows in the table. Should there be?

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '>"$.url" = ? limit 1' at line 1 (SQL: select * from `translations` where `entity_type` = Yab\Quarx\Models\Page and `entity_data`->"$.url" = home limit 1)

**Comment by mlantz** [comment]
What version of MySQL are you using?

**Comment by chadpriddle** [comment]
5.6.34

**Comment by chadpriddle** [comment]
I can access the login page domain/login and navigate around, add posts, pages, widgets but it seems that anything that is trying to access the Page model with the translations I get an error. I get the error when access the the root directory, when I create a page and click "Preview", basically anything that tries to load the root directory and not the domain.com/quarx dashboard. Everything on the dashboard seems to be working correctly.

**Comment by mlantz** [comment]
Yeah the problem was that I never tested the translations with MySQL 5.6 only 5.7. Its a JSON request so I suspect that 5.6 is causing the problem. I have a fix in place now, I'll release it tonight.
