### ISSUE TITLE
Failed to create role

### ISSUE THREAD

**Issue by chadpriddle** [GrafiteInc/CMS#36]
Trying to create a new role and get this error with the following inputs:

Name: editor
Label: Editor

Error:
Exception in RoleService.php line 107:
Failed to create role

    public function create($input)
    {
        try {
            $input['permissions'] = implode(',', array_keys($input['permissions']));
            return $this->model->create($input);
        } catch (Exception $e) {
            throw new Exception("Failed to create role", 1);
        }
    }

I'm logged in as the root admin

**Comment by chadpriddle** [comment]
I commented this and it worked:

    //$input['permissions'] = implode(',', array_keys($input['permissions']));

**Comment by mlantz** [comment]
Thanks for catching that, I've implemented some fixes. Its actually part of Laracogs that gets added to the app when you use the 'setup' command.
