### ISSUE TITLE
FAQ page from theme generator requests missing widget

### ISSUE THREAD

**Issue by fwallen** [GrafiteInc/CMS#38]
The template for the FAQ page at PublishedAssets/Theme/resources/themes/themeTemplate/faqs/all.blade.php requests the 'sample' widget on line 9. The widget is not created initially, so the page will fail in QuarxService when it accesses a null object. A more graceful fail would be nice, but perhaps a simpler solution might be creating the sample widget as part of the theme generation.

**Comment by mlantz** [comment]
Thanks, I've updated the theme templates, I'll push the fix with the next release
