### ISSUE TITLE
Composer Fails on graham-campbell/markdown Dependency

### ISSUE THREAD

**Issue by humbugz** [GrafiteInc/CMS#40]
I tried to do a fresh install of Quarx and hit a composer conflict:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yab/quarx v2.2.0 requires graham-campbell/markdown ^6.1 -> satisfiable by graham-campbell/markdown[v6.1.0].
    - yab/quarx v2.2.1 requires graham-campbell/markdown ^6.1 -> satisfiable by graham-campbell/markdown[v6.1.0].
    - yab/quarx v2.2.10 requires graham-campbell/markdown ^6.1 -> satisfiable by graham-campbell/markdown[v6.1.0].
    - yab/quarx v2.2.11 requires graham-campbell/markdown ^6.1 -> satisfiable by graham-campbell/markdown[v6.1.0].
    - yab/quarx v2.2.12 requires graham-campbell/markdown ^6.1 -> satisfiable by graham-campbell/markdown[v6.1.0].
    - yab/quarx v2.2.2 requires graham-campbell/markdown ^6.1 -> satisfiable by graham-campbell/markdown[v6.1.0].
    - yab/quarx v2.2.3 requires graham-campbell/markdown ^6.1 -> satisfiable by graham-campbell/markdown[v6.1.0].
    - yab/quarx v2.2.4 requires graham-campbell/markdown ^6.1 -> satisfiable by graham-campbell/markdown[v6.1.0].
    - yab/quarx v2.2.5 requires graham-campbell/markdown ^6.1 -> satisfiable by graham-campbell/markdown[v6.1.0].
    - yab/quarx v2.2.6 requires graham-campbell/markdown ^6.1 -> satisfiable by graham-campbell/markdown[v6.1.0].
    - yab/quarx v2.2.7 requires graham-campbell/markdown ^6.1 -> satisfiable by graham-campbell/markdown[v6.1.0].
    - yab/quarx v2.2.8 requires graham-campbell/markdown ^6.1 -> satisfiable by graham-campbell/markdown[v6.1.0].
    - yab/quarx v2.2.9 requires graham-campbell/markdown ^6.1 -> satisfiable by graham-campbell/markdown[v6.1.0].
    - Conclusion: don't install graham-campbell/markdown v6.1.0
    - Installation request for yab/quarx ^2.2 -> satisfiable by yab/quarx[v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.12, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9].

**Comment by humbugz** [comment]
... aaaaand it's because I was installing against Laravel 5.4 instead of 5.3. Sorry about that.

Any thoughts on when Quarx will officially support 5.4? Thanks!

**Comment by mlantz** [comment]
End of the week is the goal

**Comment by humbugz** [comment]
Awesome, thank you @mlantz!
