### ISSUE TITLE
Missing TeamController

### ISSUE THREAD

**Issue by dolcy** [GrafiteInc/CMS#41]
Great package. After installing Quarx (simple mode) on Laravel 5.3 via Homestead, the follow error comes up with route:list command:

`[ReflectionException]
  Class App\Http\Controllers\TeamController does not exist
`

**Comment by mlantz** [comment]
double check the routes files, the quarx setup must have missed removing it, once you remove the route the problem should be solved

**Comment by dolcy** [comment]
Thanks.
