### ISSUE TITLE
Errors with Mix with install under L5.4?

### ISSUE THREAD

**Issue by humbugz** [GrafiteInc/CMS#42]
I tried creating a fresh install of Quarx using the Simple Setup method on a clean Laravel 5.4 installation and run into errors when running the last step, npm run dev:

`npm run dev`
`ERROR  Failed to compile with 3 errors`
`error  in ./resources/assets/sass/app.scss`
`Module build failed:`
`@import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap";`
`^`
`      File to import not found or unreadable: node_modules/bootstrap-sass/assets/stylesheets/bootstrap.`
`Parent style sheet: /{my-file-path}/resources/themes/default/assets/sass/_theme.scss`
`      in /{my-file-path}/resources/themes/default/assets/sass/_theme.scss (line 7, column 1)`
` @ ./resources/assets/sass/app.scss 4:14-248`
` @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss`

Any ideas why this might be happening?

Thank you!

**Comment by mlantz** [comment]
did you do npm install first?

**Comment by humbugz** [comment]
Hi @mlantz, yes, absolutely. The install portions runs as expected. Just to be sure I did try it a few times from scratch just in case... but it failed the same way each time.

**Comment by mlantz** [comment]
try publishing the default theme then running the npm run dev, it may be something broken on the theme publishing

**Comment by humbugz** [comment]
Good call, thank you! That seems to have solved it.
