### ISSUE TITLE
Saving an image through the dashboard in S3, does not display the image

### ISSUE THREAD

**Issue by inlinkz** [GrafiteInc/CMS#43]
I am trying to set up Quarx to use S3 for the blog/pages images but when I add an image to the dashboard, 
it gets uploaded normally to S3 but when I go to view the images (modules/images/index.blade.php), i get blanks.

the `FileService::filePreview($image->location)` provides a relative path to the image instead of the absolute path that S3 would be. 

Shouldn't there be `Storage::disk(Config::get('quarx.storage-location', 'local'))` prepending the previewed filename?

Thank you in advance.

**Comment by mlantz** [comment]
I'll look into this tonight, thanks

**Comment by inlinkz** [comment]
Thanks! Just let me know if I can be of any help!

**Comment by mlantz** [comment]
Hey I fixed it I believe, will push version update today

**Comment by mlantz** [comment]
K, latest tag should have it solved. Sorry for the delay.
