### ISSUE TITLE
Issue when using command to create a new module

### ISSUE THREAD

**Issue by mip-ro** [GrafiteInc/CMS#47]
Hello. 
I am on version 2.3.4 and when I am running the commands : php artisan module:crud "name" or php artisan module:make "name", i receive this error : 
```
file_get_contents(/var/www/html/quarxLaravel/vendor/yab/quarx/src/Console/../Templates/CRUD/provider.txt): failed to open stream: No such file or directory
```
I found the file that the error talks about in the 
```
/vendor/yab/quarx/src/Templates/CRUD/Provider.txt 
```
The error appears because the name of the file called is with a lower case "p" and the actual file name is with a higher case "P".
The File is called in ModuleCrud.php:202

Thanks

**Comment by mlantz** [comment]
Oops fix coming soon
