### ISSUE TITLE
Error at module creation

### ISSUE THREAD

**Issue by mip-ro** [GrafiteInc/CMS#48]
When i'm trying to create a module, i receive an error and after this Laravel is broken

  Steps that i've made: 

    - fresh laravel install

    - composer require yab/quarx

    - add 'Yab\Quarx\QuarxProvider::class,' to my Provider

    - php artisan vendor:publish --provider="Yab\Quarx\QuarxProvider"

    - run php artisan quarx:setup (+ npm install)

    - i added this to my composer "Quarx\\": "quarx/",

    - i made composer dump-autoload -o and composer install

    - the package works ok until now

    - i want to make a new module

    - i changed the ModuleCrud.php on line 202 to get the right file("P" letter as i said on previous issue)

    - then i run artisan module:crud Groups

    - i receive 
       *** You will need to publish your module to make it available to your vistors:
        php artisan module:publish Groups
        Add this to your app/Providers/RouteServiceProver.php in the mapWebRoutes method:
        require base_path('routes/groups-web.php');
        You may wish to add this as your testing database
        'testing' => [ 'driver' => 'sqlite', 'database' => ':memory:', 'prefix' => '' ],
        Module for Group is done. ***

    - question: need to have routes/groups-web.php? because is not generated by the command

    - from this point I CAN'T START laravel. any command return this:
      ***  PHP Fatal error:  Class '\Quarx\Modules\Groups\GroupsModuleProvider' not found in /var/www/html/laravelQuarx/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 606
       [Symfony\Component\Debug\Exception\FatalErrorException]       
            Class '\Quarx\Modules\Groups\GroupsModuleProvider' not found  ***

    -  also i saw that in kernel.php on protected $routeMiddleware i have two times the
           *** 'quarx' => \App\Http\Middleware\Quarx::class,
		'quarx-api' => \App\Http\Middleware\QuarxApi::class,
		'quarx-analytics' => \Yab\Quarx\Middleware\QuarxAnalytics::class,
		'quarx-language' => \App\Http\Middleware\QuarxLanguage::class,
		'admin' => \App\Http\Middleware\Admin::class,
		'active' => \App\Http\Middleware\Active::class,***
 not sure that is ok. i guess one time is ok.

**Comment by fwallen** [comment]
I am having the same issue with `make:module`
Deleting the newly-created folder in `quarx\modules` will free the app up again, however.

**Comment by mlantz** [comment]
Did you do a composer dump?

It seems like its an issue with composer not being updated thusly missing the provider

**Comment by mlantz** [comment]
I just released some updates to the module builder, please try one more time and see if it works, also please check the composer dump. I appreciate any feedback thanks.

**Comment by fwallen** [comment]
Got the latest and was able to generate a crud module. Executed `composer dump` followed by `artisan module:publish Funnels` (using my module name) and received the following error: `Class '\Quarx\Modules\Funnels\FunnelsModuleProvider' not found`

Namespaces are correct, but in `QuarxModuleProvider`, this line `$this->app->register('\Quarx\Modules\\'.ucfirst($module).'\\'.ucfirst($module).'ModuleProvider');` cannot find it.

**Comment by mlantz** [comment]
Do me a favor and manually edit it to remove the first backslash

**Comment by mip-ro** [comment]
if you read this, please make same change on /ModuleMake.php. same issue with the "P" letter

**Comment by mip-ro** [comment]
regarding the backslash, not working. 

 "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/",
            "Quarx\\": "quarx/"
        }
    },

this is the piece from composer.json. but seems to be in right place.

**Comment by mip-ro** [comment]
after some time spent on it, only way that seems to work well is:
public function register()
    {
        if (Config::get('quarx.load-modules', false)) {
            $modulePath = base_path(Config::get('quarx.module-directory').'/');
            $modules = glob($modulePath.'*');
            
            foreach ($modules as $module) {                
                if (is_dir($module)) {
                    $module = lcfirst(str_replace($modulePath, '', $module));
                    
                    $module = ucfirst($module);
                    $str_module = "\Quarx\Modules\%module\%moduleModuleProvider";
                    $str_module = str_replace('%module',$module,$str_module);
                    
                    $this->app->register($str_module);                    
                }
            }            
        }
    }

not sure why escaped backslash not work.
the first backslash is ok to be there.
i hope this will help. 
Thanks for your time.

P.S: composer dump is mandatory

**Comment by mlantz** [comment]
Updated all around, and fixed a small issue with the templates and the dropzone stuff FYI

**Comment by jonasof** [comment]
I am still getting the same problem here (php 5.6, composer 1.4.2,  quarx 3.2.25, linux). Changing the composer.json, from:

```
"psr-4": {
    "App\\": "app/",
    "Quarx\\": "quarx/"
}
```

to:

```
"psr-4": {
     "App\\": "app/",
     "Quarx\\": "quarx/",
     "Quarx\\Modules\\": "quarx/modules/"
 }
```

And running "composer dump" solved the issue. I think the composer autoloader is looking for the folder "quarx/Modules" and then not finding the class, while QuarxModuleProvider find it.
