### ISSUE TITLE
menu entries for a new created module

### ISSUE THREAD

**Issue by mip-ro** [GrafiteInc/CMS#49]
I'm not really sure that is an issue but from what i understand:
- in vendor/yab/quarx/src/Services/ModuleService.php i have a foreach which render modules from quarx module directory(which is ok because my modules are there) and after this load what i have in config('quarx.modules')(which i'm not sure what contain; can't see in config/quarx.php). i believe what i have in config on active-core-modules are automatically loaded.
the idea is if i create a module, in admin menu appear two times(at least for CRUD modules). no time now to see exactly. maybe i'm wrong.

**Comment by mlantz** [comment]
When you have a chance can you give me more info on this, I'm a little confused

**Comment by mip-ro** [comment]
i've created a new crud module and when i go to admin part, in the left menu, i have the new module created two times. Categories and News modules for test, then two times: 
![screenshot_20170306_1054485](https://cloud.githubusercontent.com/assets/2270416/23602968/adffad2c-025b-11e7-8f0d-e770e5ea47b6.png)

**Comment by mlantz** [comment]
I cant replicate this.

**Comment by mip-ro** [comment]
Strange!
in ModuleService.php 
` $modulePath = base_path(config('quarx.module-directory').'/');
 $modules = glob($modulePath.'*');`

$modules contain 
array:2 [▼
  0 => "/var/www/html/quarxLaravel/quarx/modules/Categories"
  1 => "/var/www/html/quarxLaravel/quarx/modules/News"
]

and on if, on config('quarx.modules') i have:
array:2 [▼
  "categories" => array:2 [▼
    "asset_path" => "/var/www/html/quarxLaravel/quarx/modules/Categories/Assets"
    "url" => "categories"
  ]
  "news" => array:2 [▼
    "asset_path" => "/var/www/html/quarxLaravel/quarx/modules/News/Assets"
    "url" => "news"
  ]
]

so, loaded two times same thing. 
Please take a look in that file and you will see.

Maybe is something from config but: 
if (!is_dir($modulePath.$module)) {
                    $menu .= view($module.'::menu');
                }
is a condition which is accomplished. if you will add ucfirst  to the $module(as you did in foreach) will work properly.

thanks a lot! :+1:

**Comment by mlantz** [comment]
Hey no problem, thanks for narrowing this down. It looks like an issue that arose from my backwards compatibility with old modules which didnt use the `config('quarx.modules')` system that I use now. Fix is and I'll push the update tonight

**Comment by mip-ro** [comment]
thank you!

**Comment by mlantz** [comment]
Released

**Comment by karneaud** [comment]
I believe I am experiencing a similar issue here with the latest installation

both

```
 foreach ($modules as $module) {
            if (is_dir($module)) {
                $module = lcfirst(str_replace($modulePath, '', $module));
            	if (file_exists($modulePath.ucfirst($module).'/Views/menu.blade.php')) {
                	$menu .= view($module.'::menu');
                }
            }
        }
```
and
```
        if (is_array(config('cms.modules'))) {
            foreach (config('cms.modules') as $module => $config) {
                if (!is_dir($modulePath.ucfirst($module))) {
                    $menu .= view($module.'::menu');
                }
            }
        }
```

Are producing errors such as

> No hint path defined for [packageAirwayBills]. (View: /var/www/html/resources/views/vendor/cms/dashboard/panel.blade.php

Unless I set my namespaces of my views for my custom modules like...

```
$this->app->view->addNamespace('packageAirwayBills', __DIR__.'/Views');
        $this->app->view->addNamespace('package_airwaybills', __DIR__.'/Views');

        // Configs
        $this->app->config->set('cms.modules.package_airwaybills', include(__DIR__.'/config.php'));
```

So now it gets outputted twice. Why are we `glob`bing the modules directory yet retrieving the modules form the config???

**Comment by REPTILEHAUS** [comment]
Im getting this issue too, its pretty impossible to use this package in a production setup
