### ISSUE TITLE
Exception on demo

### ISSUE THREAD

**Issue by Metrakit** [GrafiteInc/CMS#54]
hi,

When i'm trying to login into your demo i got this error when I'm redirecting to "https://demo.quarxcms.com/quarx/dashboard" : 

> ErrorException in BaseProvider.php line 178:
file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known (View: /home/forge/demo.quarxcms.com/releases/1/vendor/yab/quarx/src/Views/dashboard/analytics-internal.blade.php)

When I refresh It's work.

**Comment by mlantz** [comment]
I think it was a broad issue that others were getting too. It seems to have stopped but I'll keep an eye on it thanks.

**Comment by Metrakit** [comment]
You're welcome :)
