### ISSUE TITLE
Small issue when trying to save content and leaving the content field empty (noticed when saving pages)

### ISSUE THREAD

**Issue by mip-ro** [GrafiteInc/CMS#55]
Hello.

While trying to save multilanguage pages, if i do not put any data in the "Content" field it saves the content in the DB but when it redirects the page i got an error 
```
Method Yab\Quarx\Services\Normalizer::__toString() must return a string value (View: /var/www/html/laravel-logicr/resources/views/vendor/quarx/modules/blogs/edit.blade.php)
```
this is done because in that method in the __toString() method it just returns the value of the field
```
return $this->value;
```
but in the DB it is saved as null, for me the fastes solution was to change that line in 
```
return $this->value ? $this->value : '';
```
so that it return an empty string if it receives a null value.

Have a good day

**Comment by mlantz** [comment]
This is now resolved in the latest release
