### ISSUE TITLE
Class Quarx\PagesController does not exist

### ISSUE THREAD

**Issue by ghost** [GrafiteInc/CMS#58]
Not sure what the issue is here.  I followed all the install steps.  I created a page in the admin, but when trying to view the page, I get this exception.

Everything looks right.  The route is there using the Quarx namespace, and the PagesController is under the Quarx directory and references the Quarx namespace.

I am running Laravel 5.4

<img width="1394" alt="screen shot 2017-04-01 at 7 55 39 pm" src="https://cloud.githubusercontent.com/assets/9053151/24583843/7b586994-1715-11e7-9bb7-44f7f099656c.png">

**Comment by mlantz** [comment]
Can you show me the RouteServiceProvider?

**Comment by ghost** [comment]
`<?php

namespace App\Providers;

use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;

require base_path('routes/quarx.php');

class RouteServiceProvider extends ServiceProvider
{
    /**
     * This namespace is applied to your controller routes.
     *
     * In addition, it is set as the URL generator's root namespace.
     *
     * @var string
     */
    protected $namespace = 'App\Http\Controllers';

    /**
     * Define your route model bindings, pattern filters, etc.
     *
     * @return void
     */
    public function boot()
    {
        //

        parent::boot();
    }

    /**
     * Define the routes for the application.
     *
     * @return void
     */
    public function map()
    {
        $this->mapApiRoutes();

        $this->mapWebRoutes();

        //
    }

    /**
     * Define the "web" routes for the application.
     *
     * These routes all receive session state, CSRF protection, etc.
     *
     * @return void
     */
    protected function mapWebRoutes()
    {
        Route::middleware('web')
             ->namespace($this->namespace)
             ->group(base_path('routes/web.php'));
    }

    /**
     * Define the "api" routes for the application.
     *
     * These routes are typically stateless.
     *
     * @return void
     */
    protected function mapApiRoutes()
    {
        Route::prefix('api')
             ->middleware('api')
             ->namespace($this->namespace)
             ->group(base_path('routes/api.php'));
    }
}
`

**Comment by mlantz** [comment]
2 Things here, the `setup` command would have done this but I forgot to update some of the docs. You need to replace `->group(base_path('routes/web.php'));` with:

```
->group(function() {
    require base_path('routes/web.php');
    require base_path('routes/quarx.php');
});
```

By simply placing it in the top of your file, the namespaces are broken and the web middleware is missing.

**Comment by ghost** [comment]
Thanks for all your work.  That did it.
