### ISSUE TITLE
Hiding Modules from navbar

### ISSUE THREAD

**Issue by fwallen** [GrafiteInc/CMS#61]
Is there a method for not displaying modules in the live site navbar? I want to be able to use the module generator, but not add that created module to the navbar.

**Comment by mlantz** [comment]
just remove the menu blade file from the module view folder - it should disappear then

**Comment by fwallen** [comment]
@mlantz,
Correct, that will remove it from the sidebar menu in the dashboard, but I'm referring to the navbar in the 'live' view. The `@modules()` directive used in `navigation.blade.php` does not appear to take any parameters to filter the list. I didn't want to just drop it's use if there was functionality I am unaware of. I like the idea of having control of modules in the admin menu, by modifying `menu.blade.php`.

**Comment by mlantz** [comment]
The modules one should follow the active modules list, if you comment out active ones then they should not show up, if not I'll add that feature

**Comment by mlantz** [comment]
Did that solve the problem?

**Comment by mlantz** [comment]
Looks like there was nothing that fixed that. I added it now to the `@menu(['moduleName'])` or you can add to the module config `'is_ignored_in_menu' => true` which should make it easy :)
