### ISSUE TITLE
Hiding frontend edit buttons

### ISSUE THREAD

**Issue by ghost** [GrafiteInc/CMS#62]
Can I hide the frontend edit buttons when logged in as an admin?

**Comment by mlantz** [comment]
Yes they are in the templates you would have to remove the buttons, including the one in the footer :)

**Comment by ghost** [comment]
I don't see them in the templates, for instance I see the menu module adds it in the MenuServiceTrait.  Can I override that?  If the future maybe add a unique class to those so we can hide them in the css.

**Comment by mlantz** [comment]
In the theme 'templates' there are blade directives that look like `@edit('pages', $page->id)` you need to remove those from the theme to get rid of them :) CSS would also be good I'll make a note thanks.

**Comment by ghost** [comment]
Sorry to bother.  I see this for my modules and the publish assets, but not for widgets or menus

**Comment by mlantz** [comment]
Hmmm, it seems thats built into the menus and widgets.... I could make an override option. Do you think it should be config option or menu / widget specific?

**Comment by ghost** [comment]
I personally think a config option would be good enough.  Thank you.
