### ISSUE TITLE
How to add custom fields to default quarx modules ?

### ISSUE THREAD

**Issue by Mariana-Marica** [GrafiteInc/CMS#63]
I want to add custom fields to default quarx modules, like menu, example: i want to add field for menu position. 
How do i override the $fillable array from the default Menu module, to also save info from my new added field ?

**Comment by mlantz** [comment]
I did some digging into Laravel's code base and turns out I didn't account for this in Quarx. I have a solution I've put together which I'll try and release tonight.

**Comment by Mariana-Marica** [comment]
Thank you ! 
I will wait for the solution and after trying it, i will give you feedback.
