### ISSUE TITLE
Multilanguage case: improper language url and correspondent tab when editing a module item

### ISSUE THREAD

**Issue by Mariana-Marica** [GrafiteInc/CMS#65]
When editing a module item in admin panel -> the form fields from the first language are displayed ("default-language" in quarx.php), but the last language tab is highlighted and the correspondent language url is not being loaded

**Comment by mlantz** [comment]
I'll need a bigger description of this, can you provide example urls and some screenshots possibly. Its hard to isolate exactly what isnt working correctly for you.

**Comment by Mariana-Marica** [comment]
I provide steps and screenshot with problem encountered:
- i have set in app.php 'locale' => 'fr', and 'fallback_locale' => 'en', & in quarx.php the following:
```
    'auto-translate' => true,
    'default-language' => 'fr',
    'languages' => [
        'fr' => 'français',
        'en' => 'english',
    ],
```
- i create a page 'test-page' and then, after submit i am on the same page, on edit case;
- after submit the url has no lang param regarding the actual language i am positioned on (it's just quarx/pages/{id}/edit with no language) and the highlighted language tab is always the last one, in my case 'english';
- on create and update if i write some content, it will be saved for first language, 'french' in my case, although english tab is active; if i don't specifically click a language tab, the url will not appear with corresponding lang param '?lang=fr' and the corresponding lang tab is not highlighted;
![edit](https://cloud.githubusercontent.com/assets/24438362/25610657/c84995be-2f2c-11e7-8cfe-20ceacbe57da.png)

**Comment by mlantz** [comment]
Awesome, thanks, replicating this setup - I'm getting the same issue, I'll see what I can fix today

**Comment by mlantz** [comment]
K, solved it, there were a couple issues. Will be pushing update today

**Comment by Mariana-Marica** [comment]
Thank you !

**Comment by Mariana-Marica** [comment]
I still see the same behavior !

**Comment by mlantz** [comment]
What version do you have in the bottom corner? and did you replace your `resources/views/vendor/quarx` views?

**Comment by Mariana-Marica** [comment]
I updated the dependencies just today and i have the latest Quarx version 2.3.21. I don't really know what exactly to replace, why and where, can you give more info on this pls ?

**Comment by Mariana-Marica** [comment]
- yes, i should have published the vendor by running 'php artisan vendor:publish' that replaces ```resources/views/vendor/quarx``` with the ones from ```project_name/vendor/yab/quarx/src/Views```; 
- it now works for default quarx modules, but i can mention that after creating a new module, the language tabs from custom module edit in admin panel are still loaded the same (because of ```Quarx::config('quarx.languages'))``` instead of ```config('quarx.languages'))```):
```
        <ul class="nav nav-tabs">
            @foreach(config('quarx.languages', Quarx::config('quarx.languages')) as $short => $language)
                <li role="presentation"
                    @if (request('lang') == $short || is_null(request('lang')) && $short == Quarx::config('quarx.default-language'))) class="active" @endif>
                    <a href="{{ url('quarx/blogcategories/'.$blogcategory->id.'/edit?lang='.$short) }}">{{ ucfirst($language) }}</a>
                </li>
            @endforeach
        </ul>
```

**Comment by mlantz** [comment]
```
@foreach(config('quarx.languages') as $short => $language)
    <li role="presentation" @if (request('lang') == $short || is_null(request('lang')) && $short == config('quarx.default-language'))) class="active" @endif><a href="{{ url('quarx/blog/'.$blog->id.'/edit?lang='.$short) }}">{{ ucfirst($language) }}</a></li>
@endforeach
```

This should be accurate. I have not yet made a means of setting modules as multilingual but its on my todo list. 

You will also need to make sure your module uses `Yab\Quarx\Traits\Translatable` also check out the BlogRepository and look at the update method to make sure you're saving the languages
