### ISSUE TITLE
Error when deploying to production server.

### ISSUE THREAD

**Issue by ghost** [GrafiteInc/CMS#66]
I am getting the following error when trying to run composer update on the production server.  It is save php and composer version as dev server.   This class does indeed exist.

[2017-05-01 18:48:30] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class '\Quarx\Modules\Affiliates\AffiliatesModuleProvider' not found in /data/www/sites/staging.loanmls.com/releases/20170501165423/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:612
Stack trace:
#0 /data/www/sites/staging.loanmls.com/releases/20170501165423/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(570): Illuminate\Foundation\Application->resolveProvider('\\Quarx\\Modules\\...')
#1 /data/www/sites/staging.loanmls.com/releases/20170501165423/vendor/yab/quarx/src/Providers/QuarxModuleProvider.php(24): Illuminate\Foundation\Application->register('\\Quarx\\Modules\\...')
#2 /data/www/sites/staging.loanmls.com/releases/20170501165423/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Yab\Quarx\Providers\QuarxModuleProvider->register()
#3 /data/www/sites/staging.loanmls.com/releases/20170501165423/vendor/yab/quarx/src/QuarxProvider.php(134): Illuminate\Foundation\Application->register(Object(Yab\Quarx\Providers\QuarxModuleProvider))
#4 /data/www/sites/staging.loanmls.com/releases/20170501165423/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Yab\Quarx\QuarxProvider->register()
#5 /data/www/sites/staging.loanmls.com/releases/20170501165423/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\Foundation\Application->register(Object(Yab\Quarx\QuarxProvider))
#6 /data/www/sites/staging.loanmls.com/releases/20170501165423/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(549): Illuminate\Foundation\ProviderRepository->load(Array)
#7 /data/www/sites/staging.loanmls.com/releases/20170501165423/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#8 /data/www/sites/staging.loanmls.com/releases/20170501165423/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#9 /data/www/sites/staging.loanmls.com/releases/20170501165423/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(267): Illuminate\Foundation\Application->bootstrapWith(Array)
#10 /data/www/sites/staging.loanmls.com/releases/20170501165423/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(114): Illuminate\Foundation\Console\Kernel->bootstrap()
#11 /data/www/sites/staging.loanmls.com/releases/20170501165423/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 {main}

**Comment by mlantz** [comment]
This is tough to make an accurate assessment. Is the module in the modules directory? Is the composer file correct with the `"Quarx\\Modules\\": "quarx/modules/",` addition to the autoload?

Does the same error occur on your dev server?

**Comment by ghost** [comment]
This is a new site, so I only have local and prod.  The error doesn't occur on local.

The module is in the quarx/modules

The autoload looks like this

    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/",
            "Quarx\\": "quarx/"
        }
    },

**Comment by mlantz** [comment]
try doing `"Quarx\\Modules": "quarx/modules"` it may be an issue since Modules isnt capitalized the and if your building locally on a Mac the system wont care but on production it will care

**Comment by ghost** [comment]
That was it.  Thank you for the help.
