### ISSUE TITLE
Menu issues: menu admin error & front display menu links to unpublished pages

### ISSUE THREAD

**Issue by Mariana-Marica** [GrafiteInc/CMS#67]
- in admin when accessing a menu that has a link to a deleted page, error returns because it tries to display a non-existent page (PageService.php line 49) in links menu listing;
- after adding a menu link to an unpublished page in admin, the unpublished page is displayed in frontend menu; also, i don't think the pages are retrieved according to publish date being < now() because their content is not displayed when accessing the page (404)

**Comment by mlantz** [comment]
Ok, I found the root of both of these and the fixes will be coming with the next release

**Comment by Mariana-Marica** [comment]
Thanx
