### ISSUE TITLE
Unable to save content for template blocks

### ISSUE THREAD

**Issue by johnmans** [GrafiteInc/CMS#68]
After saving (updating) a page, the content of my template blocks is not saved in the database. The 'blocks' field contains a json of empty values (which means that something is saved at some point):

`{"main":"","test":""}` ('main' and 'test' are the block slugs)

The data ('block_main' and 'block_test') is there while the form is being submitted.
It is just not saved in the database.

Do you know which might be the issue..?

**Comment by mlantz** [comment]
Will look in and solve this - I'm working on getting a release out today :)

**Comment by mlantz** [comment]
Can you give me an example of the content in your blocks - I'm having a hard time replicating

**Comment by johnmans** [comment]
It is plain text, nothing special. If you find it hard to replicate, then there could be a problem with my setup I guess... I will try to sort it out :). Thank you for your time and for your work!

**Comment by mlantz** [comment]
I'll do my version update in a bit which may have actually solved the problem in itself, hence I cant replicate :)

**Comment by johnmans** [comment]
Yes, the latest update solved it 👍
