### ISSUE TITLE
FormMaker

### ISSUE THREAD

**Issue by bgies** [GrafiteInc/CMS#69]
I'm just evaluating this CMS, but thought I'd report this issue... when using the FormMaker->getTableColumns... the getDoctrineColumn needs to be passed the DB prefix... I changed line 368 in FormMaker.php, and it fixed it for me... but I don't know that it's the correct fix. 

I'm using Homestead (php 7.1) on Windows.. my Laravel db prefix is set.. the Quarx db prefix is blank. 

`        foreach ($tableColumns as $column) {
            if (!in_array($column, $badColumns)) {
                $type = DB::connection($this->connection)->getDoctrineColumn(DB::connection($this->connection)->getTablePrefix().$table, $column)->getType()->getName();
                $tableTypeColumns[$column]['type'] = $type;
            }
        }
`

On another note, where should I ask questions... I don't see a forum

**Comment by mlantz** [comment]
I'm always available on LaraChat Slack but I've never thought about putting a forum together. I'll fix the FormMaker today and get an updated release pushed. Thanks.

**Comment by mlantz** [comment]
Latest FormMaker package release has a fix
