### ISSUE TITLE
S3 upload issue

### ISSUE THREAD

**Issue by artemartemov** [GrafiteInc/CMS#70]
Hey there,

When I setup with S3 I keep on getting a pesky little error "The location field is required" 

I have entered the proper key/secret/bucket into my .env file but not sure how to bypass this.

Only thing I am thinking is that I am working locally through homestead but can't see why that would cause an issue.

**Comment by mlantz** [comment]
I'm unable to replicate this. 

AWS_KEY=
AWS_SECRET=
AWS_REGION=
AWS_BUCKET=

And you need to do:

`composer require league/flysystem-aws-s3-v3`

Then just set the quarx config to:

`'storage-location' => 's3'`

**Comment by artemartemov** [comment]
Okay great, I actually was writing the region wrong and now am seeing the uploads complete no problem.

One other issue now - I can see the image fine in the images index, however upon clicking edit - the preview on that page is looking for a local version of the image that it is not finding. 

Should there also be a local copy of said image, or should it be pulling in from S3?

**Comment by artemartemov** [comment]
It looks like it is trying to look for a local version of that image upon edit

`<img src="http://quarx.local/storage/images/3bd73c266c70a1be9e1a3828aff20d7f.jpg">`

**Comment by mlantz** [comment]
Just noticed that - I'll get that fixed asap thanks

**Comment by mlantz** [comment]
You can fix locally pretty quickly - just change line 14 `resources/views/vendor/quarx/modules/images/edit.blade.php` to: `<img src="{!! $images->url !!}" />`

**Comment by artemartemov** [comment]
Ah okay awesome, I figured it was something simple. Thanks so much for getting back so quick

Just one more question - now that I am on s3 it seems that the blade tags are still pointing to your local and not s3. seems to be hitting `/storage/images/`

**Comment by mlantz** [comment]
Yup thats also a bug - got a fix in the works will release updates tonight thx.

**Comment by artemartemov** [comment]
Great, looking forward - thanks so much
