### ISSUE TITLE
 Error Exception when accessing admin panel after creating a module with a camel case name

### ISSUE THREAD

**Issue by Mariana-Marica** [GrafiteInc/CMS#73]
If a custom module is created with camel case name(for example BlogTest), then the error below will appear in admin panel (dashboard route): 
![error_module_name](https://cloud.githubusercontent.com/assets/24438362/26652617/2457dbac-4659-11e7-8c35-df29191b91fb.png)
This is not the case when only the first letter is capital.

**Comment by mlantz** [comment]
Ok, I think I have a solution for this. I'll release updates this weekend.

**Comment by mlantz** [comment]
Hey @Mariana-Marica would you be able to confirm that the latest version is working as expected.

**Comment by Mariana-Marica** [comment]
I will check it out soon, and let you know !

**Comment by Mariana-Marica** [comment]
I tested your fix for this matter on quarx v. 2.3.24 and it works !
