### ISSUE TITLE
FAQ multi lingual

### ISSUE THREAD

**Issue by ghost** [GrafiteInc/CMS#76]
I am pulling various counts of FAQs throughout areas of our site using
$faqs = app('Yab\Quarx\Models\FAQ')::where('is_published', 1)
                    ->orderBy('published_at', 'desc')
                    ->take($limit)
                    ->get();

I tried using the TranslationRepository getEntitiesByTypeAndLang when the App locale is not en, but it is not returning any results.

How are we supposed to be pulling the translations?

**Comment by mlantz** [comment]
Thats odd it works in my demo app for translations.

An entry should be attainable by using: `$this->translationData($lang)` with the language as the variable. So for each FAQ you can access its transalation via that method on the instance.

ex.

```app(Yab\Quarx\Models\FAQ::class)->find(1)->translationData('fr');```

**Comment by ghost** [comment]
Thank you for getting back to me.  I really do appreciate it.  

So for me
This returns an FAQ:
app('Yab\Quarx\Models\FAQ')->find(1);

These both return null:
app('Yab\Quarx\Models\FAQ')->find(1)->translationData('en');
app('Yab\Quarx\Models\FAQ')->find(1)->translationData('es');

**Comment by ghost** [comment]
Ok, I did some more digging.  It turns out, not all of the FAQs have publish 'es' translations, and it happens that the first FAQ is one that does not.

If I follow your style in the view ($event->translationData(config('app.locale'))->title), this will through an exception if all the entities of this type don't have translations.  

I added a null check to remove those from my list
