### ISSUE TITLE
this is correct?

### ISSUE THREAD

**Issue by Mathias88** [GrafiteInc/CMS#77]
`    public function apiList(Request $request)
    {
        if (Config::get('quarx.api-key') != $request->header('quarx')) {
            return QuarxResponseService::apiResponse('error', []);
        }
        return $this->imagesRepository->apiPrepared();
        return QuarxResponseService::apiResponse('success', $images);
    }`

Twice return?

**Comment by mlantz** [comment]
doh

**Comment by mlantz** [comment]
That is incorrect, fix will be pushed tonight - thanks

**Comment by Mathias88** [comment]
And please, check that you can not insert uploaded images in the edition of a blog.
Thanks!
