### ISSUE TITLE
Image uploading. "The location field is required"

### ISSUE THREAD

**Issue by johnmans** [GrafiteInc/CMS#81]
Hello,

It seems like image uploading has stopped working.
Whenever I try to save an image I get the following message:
"The location field is required"

It used to work properly in the past.
Do you know what might be the issue?

Cheers!

**Comment by ChristianOrrala** [comment]
I have the same issue, actually I'm new on quarx and images was one of the main feayures I was looking for.

**Comment by mlantz** [comment]
What version are you guys running? This was an issue that occurred recently but I thought was fixed recently. Any extra information you guys can provide would be appreciated. Thanks.

**Comment by johnmans** [comment]
The version I am using is the last one ( v2.3.26 ) via composer.

**Comment by mlantz** [comment]
Hey guys I just found this in my working copy, fix coming soon. Sorry about this.

**Comment by rossity** [comment]
@mlantz I just updated to to the JS fix (it worked, thanks!), but when I go to the "images" tab I'm getting 404s on the images I uploaded, and when I go to the posts tab and look for the file I uploaded under "Files" it gives me the "You haven't uploaded any files yet" message.

It looks like the files are stored under `storage\app\files` and images are stored under `storage/app/public/images` yet in the images tab it's trying to find files under `storage/images`

**Comment by johnmans** [comment]
Hello, I also updated to the last version and I get the following js error
 (which seemingly breaks the dropzone.js functionality)

`Uncaught ReferenceError: _appTimeZone is not defined`

**Comment by rossity** [comment]
@johnmans do you have something like `APP_TIMEZONE=America/New_York` in your .env file?

@mlantz is there a place we should be setting the correct storage directory for images/files?

**Comment by johnmans** [comment]
@rossity no, I tried adding/removing it but nothing changed

**Comment by rossity** [comment]
okay, I fixed the images displaying incorrectly. since it was a fresh L5 installation I hadn't run `php artisan storage:link` yet. All is well now!

**Comment by ChristianOrrala** [comment]
Hello, I also updated to the last version and again get the "The location field is required", I cleaned the config cache `php artisan config:cache` then the suggested `php artisan storage:link` as I think I forgot to use it in the prod environment. 

Now it's working fine.

**Comment by mlantz** [comment]
Hey @rossity @johnmans @ChristianOrrala  et al,

I'm happy to resolve things. I'm going to close this issue, if there are other issues or you feel like things are missing in the docs, please let me know and I'll do updates accordingly. Thanks for your input. :)
