### ISSUE TITLE
How are reports on the dashboard configured?

### ISSUE THREAD

**Issue by adam-jones-net** [GrafiteInc/CMS#82]
I can't see anything about this on the documentation and in the hosted demo site going into the Admin/Dashboard menu item results in a blank page with no settings to alter.

Reporting is absolutely vital to me in a laravel cms, can a little more detail on this be provided ?

**Comment by mlantz** [comment]
Admin/dashboard is a blank dashboard, nothing setup by default. The default Quarx/dashboard has the hit stats etc. The idea is that for the CMS you may be interested in hit stats but for admin you may be more interested in user activity or some other data for the dashboard :)
