### ISSUE TITLE
"This module may have been installed via composer" module:publish not publishing correctly

### ISSUE THREAD

**Issue by rossity** [GrafiteInc/CMS#84]
I get the following message when trying to run `php artisan module:publish test`

```
This module may have been installed via composer, if so please run:
php artisan vendor:publish
You will need to ensure that you copy the published views of this module in the default theme into your custom themes.
```

So I run `php artisan vendor:publish` and it seems to publish the `Publishes/app`, `Publishes/resources`, and `Publishes/routes` folders but **_not_** the `Publishes/database` folder.

**Comment by mlantz** [comment]
Based on my tests the modules are publishing fine. In order for the publish command to work as intended the Module must be in the `quarx/modules` directory or where you set the directory in the config. If its not located in there, it will assume its a package. 

Vendor publish can in many cases achieve the same result. The original Publish command was prior to the modules being more composer package based.
