### ISSUE TITLE
Theming the quarx Admin panel

### ISSUE THREAD

**Issue by lighth7015** [GrafiteInc/CMS#87]
Hi,

What would it take to add a theme to the Quarx admin site?

Thanks!

**Comment by mlantz** [comment]
It currently publishes to the `resources/views/vendor` so you could make a custom iteration and make it available for releases. We're currently exploring using Vue components as portions of the backend at the moment. 
That being said I may start exploring a simple way of implementing this.

**Comment by joshua-p-williams** [comment]
You already can change the theme in the config/quarx.php

``
'backend-theme' => 'united', // cosmo, cyborg, flatly, lumen, paper, sandstone, simplex, united, yeti
``

If you want to add custom menus as part of your package, you can hijack the quarx menu from your packages service provider and inject your own views to show up in the admin.

```
private function addQuarxMenu($menu) {                
    $packageViews = Config::get('quarx.package-menus');

    if (is_null($packageViews)) {
        $packageViews = [];
    }

    $menuView = realpath(__DIR__.'/../../resources/views/quarx/') . $menu;

    if (!in_array($menuView, $packageViews)) {
        array_push($packageViews, $menuView);
        Config::set('quarx.package-menus', $packageViews);
    }
}

protected function registerQuarxModule() {
    $this->addQuarxMenu('/getrealt/menu.php');
}
```

Then in the boot method of your packages service provider, just call it.  Example..
```
    public function boot()
    {
        $this->registerQuarxModule();        
    }
```

See line 100 [here](https://github.com/timitek/getrealt-quarx/blob/master/app/Providers/GetRealTServiceProvider.php)
for an example of how I'm doing it.

You can see the views I'm injecting into the admin dashboard [here](https://github.com/timitek/getrealt-quarx/tree/master/resources/views/quarx/getrealt)

(I'm also injecting some javascript  to bootstrap my angularjs based app into the admin section.  See line 11 of [menu.php](https://github.com/timitek/getrealt-quarx/blob/master/resources/views/quarx/getrealt/menu.php).

**Comment by mlantz** [comment]
Based on the latest release I've reduced the themes to standard and dark, I never felt right about having so many themes that never fit the UI well.

**Comment by elanclarkson** [comment]
@mlantz Hi!

I'm using Grafite (just upgraded from Quarx) and am looking to build a custom admin theme.

Could you please clarify what you mean by this?

> It currently publishes to the resources/views/vendor so you could make a custom iteration and make it available for releases.

Would editing the resources/views/vendor directly be a bad idea? I know it'll make maintenance harder as future releases come out, but isn't the point (and drawback) of publishing views etc so they can be customised as needed?

Really appreciate your advice (and your work on this package!) - thank you!

**Comment by mlantz** [comment]
Hey @elanclarkson, thanks, as it stands I have the light and dark themes available for the UI and yes customizing it via the published vendor files is a challenge for maintenance, but as it stands I have no intention of doing major changes to the Admin for several months if even any more this year. That being said, I'm always happy to review Pull Requests
