### ISSUE TITLE
artisan module:crud does not create route file

### ISSUE THREAD

**Issue by simmbiote** [GrafiteInc/CMS#88]
Running the following command should generate a route file:

`php artisan module:crud Testwidgets`

After running it provides these instructions:

> Add this to your `app/Providers/RouteServiceProver.php` in the `mapWebRoutes` method:
> require base_path('routes/testwidgets-web.php');

routes/testwidgets-web.php does not get created.

Additionally this error is thrown:

> (1/1) FatalThrowableErrorClass '\Quarx\Modules\Testwidgets\TestwidgetsModuleProvider' not found

**Comment by mlantz** [comment]
You may have missed the step: `php artisan module:publish Testwidgets` you need to do this for widgets that you make. You may have to run `composer dump-autoload` as well.
