### ISSUE TITLE
Is Quarx compatible with Laravel 5.5.1 ?

### ISSUE THREAD

**Issue by fredmj** [GrafiteInc/CMS#89]
Hi there,
Quarx seems to be a really great CMS/Blog webapp. So I would try to install it from this github repo over a fresh installed Laravael v5.5.1 but I've got some messages indicating me it's a wrong idea :

> [root@Host-002 fmjconsulting]# composer require yab/quarx
> Using version ^2.3 for yab/quarx
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: remove laravel/framework v5.5.1
>     - Conclusion: don't install laravel/framework v5.5.1
>     - yab/quarx v2.3.0 requires illuminate/support 5.4.* 

What I have done :
```bash
  233  laravel new fmjconsulting
  235  cd fmjconsulting/
  236  systemctl status firewalld.service
  237  systemctl stop firewalld.service
  238  systemctl status redis.service
  239  systemctl start redis.service
  241  systemctl status mariadb.service
  242  systemctl start mariadb.service
  243  composer require yab/quarx
  245  git clone https://github.com/YABhq/Quarx.git
  247  composer require yab/quarx
```

Is it me who doing something wrong? 
Or Is there a plan for upgrading Quarx for laravel 5.5.1 ?

Regards,

**Comment by mlantz** [comment]
Should be done this weekend.
