### ISSUE TITLE
Problem on Laravel 5.5

### ISSUE THREAD

**Issue by aimeos** [GrafiteInc/CMS#92]
Running `php artisan quarx:setup` fails because the main method is still called `fire` instead of `handle`. This also applies to some other commands as well.

Changing this, the setup process throws an exception:
```
  [ErrorException]                                                                       
  file_get_contents(.../vendor/yab/laracogs/src/Packages/Starter/Factory.txt): failed to open stream: No such file or directory                 
```

**Comment by mlantz** [comment]
I'll explore and get this sorted out. Thanks.

**Comment by mlantz** [comment]
Fixed that - Thanks. Release coming tomorrow.
