### ISSUE TITLE
InvalidArgumentException Route [login] not defined.

### ISSUE THREAD

**Issue by rogerraa** [GrafiteInc/CMS#93]
Hello..

Trying out Quarx and getting error "InvalidArgumentException Route [login] not defined." when going to /quarx/dashboard  

This is after a fresh install of laravel and by following the "Complex Setup" directions on your git page.

"Simple Setup" throws a "[ReflectionException] Method Yab\Quarx\Console\Setup::handle() does not exist" error btw. But I think you already know about that.

Thanks! trying to vet out your cms for a client project and really hoping it pans out.

**Comment by mlantz** [comment]
Hey sorry it looks like I missed some stuff in the documentation - stating that Simple Setup can only be done on an fresh Laravel install. Otherwise, you need to do the complex setup. I've updated the handle too with a new release coming tomorrow. Thanks.

**Comment by rogerraa** [comment]
Hi. I think I didn't explain clear enough.

The error happens after doing the complex setup on a fresh laravel 5.5 install. 

The error is "InvalidArgumentException Route [login] not defined"

**Comment by rogerraa** [comment]
Problem still exists..

Please set Issue to "open"

**Comment by mlantz** [comment]
Can you please provide your `routes/web.php` file

**Comment by rogerraa** [comment]
Yeah..  It's not to exciting.. Just the default route file on a refresh install..

```
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
```

Based off of your request here, and some of your documentation, I'm assuming the issue is, that the error I'm getting is normal and the Complex Setup is not intended for a fresh install.

If that is right, the confusion here is in the wording and organization of your documentation, and could use some more straight forward wording for us the unfamiliar and stupid(like myself). For example, the "Create a new Laravel application, and make a database somewhere and update the .env file" in "Installation" gave me the impression both setup methods needed a new laravel app. That should only be in the Simple Setup instructions.

More descriptive setup names for the two instructions based off the circumstances one would use them in, would also go a long way.

"Starter Setup", & "Integrating Quarx".

"Quarx Setup"
"Quarx can be setup in two ways. The Starter Setup is for brand new Laravel installations, while the Integrating Quarx is for existing Laravel applications you have already built. (Please Note: A route to the quarx/dashboard will not be created using the Integrating Quarx method)





anyway.. I hope I'm not overstepping any bounds, just some outside custome perspective. So yeah..  take it or leave it, thats my feedback..  Goodluck!

**Comment by mlantz** [comment]
Hey @rogerraa thanks for the info, I'll make some better updates to the docs. With the fixes I'm pushing to the 'setup' command this should no longer be an issue, but I'll make a note that the complex setup is expecting a basic login to already be prepared. Thanks again for the feedback.
