### ISSUE TITLE
php artisan quarx:setup still not working

### ISSUE THREAD

**Issue by aimeos** [GrafiteInc/CMS#94]
Executing `php artisan quarx:setup` still results in an exception because the Factory.txt is missing in the laracogs package:
```
php artisan quarx:setup                     
Copying routes...
Copying config...
Copying app/Http...
Copying app/Events...
Copying app/Listeners...
Copying app/Notifications...
Copying app/Models...
Copying app/Services...
Copying database...
Copying resources/views...
Copying tests...
Appending database/factory...

                                                                                         
  [ErrorException]                                                                       
  file_get_contents(/mnt/home/nose/Aimeos/test/aimeos/vendor/yab/laracogs/src/Packages/  
  Starter/Factory.txt): failed to open stream: No such file or directory                 
```

**Comment by rogerraa** [comment]
same..  

and the Complex Setup way doesn't work either.. https://github.com/YABhq/Quarx/issues/93
 Issue was closed prematurely

**Comment by fwallen** [comment]
I did not have that experience, @aimeos. I did a fresh install with 5.5 (preferred dist), followed directions to simple setup. I also did not see `Appending database/factory...`

The version of Laracogs installed for me was `2.3.3`
