### ISSUE TITLE
Quarx taking over laravel blade namespace and mucking up forms

### ISSUE THREAD

**Issue by ajoy39** [GrafiteInc/CMS#95]
I'm trying to use Quarx to handle the public-facing pages of a web app, unfortunately, it seems to be taking over my laravel collective forms. Within my member's section (which I have prefixed with /members to avoid messing with the quarx routes) I have forms generated by laravel blade with the following header

`
{!! Form::open(['action' => 'MapsController@index', 'id' => 'availability-search-form', 'method' => 'get']) !!}
`

Unfortunately, Quarx is taking over the namespacing inside this form and blade is looking for the url to generate for that form in 

Yab\Quarx\Controllers\MapsController@index not defined

resulting in not finding my controller and the page crashing. 

if I do this: 

`
{!! Form::open(['action' => '\App\Http\Controllers\MapsController@index', 'id' => 'availability-search-form', 'method' => 'get']) !!}
`

then it finds the correct controller, but as this app has already been under development for several months it would be a bit of a task to go back and add namespacing to every Collective form

Is there some way to tell Quarx that it should not inject its namespace for routes that are being handled by the laravel app itself?

**Comment by mlantz** [comment]
Hey sorry for the delay I've been on some much needed holidays. I'll take a look at this, thanks for being patient.

**Comment by mlantz** [comment]
Is there anything more you can provide? I'm testing this in a Laravel 5.5 using Quarx and putting the form in a the `resources/themes/default/pages/home.blade.php` file and it looks at the appropriate namespace for me.

**Comment by ajoy39** [comment]
Sorry, my mistake for not providing enough detail. The forms I'm concerned with are forms in an existing application that we're trying to add quarx to, they are in a view completely separate from quarx and it's themes. Even though they are not in the resources/themes folder, and the routes pointing to those views are part of our existing app, the app still tries to find the form actions in the Quarx namespace

**Comment by mlantz** [comment]
```
{!! Form::open(['action' => 'Quarx\PagesController@home', 'id' => 'availability-search-form', 'method' => 'get']) !!}
```

I have this added to the login page and it works fine....

Same with this:

```
{!! Form::open(['action' => 'User\NotificationController@search', 'id' => 'availability-search-form', 'method' => 'post']) !!}
        <input type="text">
    {!! Form::close() !!}
```

**Comment by ajoy39** [comment]
Yes the problem is my other Forms that aren't quarx based. So inside of the app that we're trying to add quarx to I have a a controller at App\Http\Controllers\MapsController. Without Quarx installed I can do 
`
{!! Form::open(['action' => 'MapsController@index', 'id' => 'availability-search-form', 'method' => 'get']) !!}
`

When we install Quarx, I can no longer load the page that this form is on because it is defaulting to the Quarx namespace (even though this page has nothing to do with Quarx and is in the separate app) 
When I add the App\Http\Controllers namespace like so
`
{!! Form::open(['action' => '\App\Http\Controllers\MapsController@index', 'id' => 'availability-search-form', 'method' => 'get']) !!}
`
The form and page work again. The issue is that we have tons of these forms scattered around our site and it's super practical to go back and edit all of our forms to add the full namespace. We can, and it works, but I'm concerned that if Adding Quarx causes our app to default to the Quarx namespace any time one isn't specifically declared then it could cause issues elsewhere that we haven't found yet.

**Comment by mlantz** [comment]
Yeah I'm at a loss right now, I can't seem to replicate it and I have no idea why that would be happening....

**Comment by ajoy39** [comment]
We finally figured this out, in the Config/App.php the Quarx service provider needs to be added BEFORE the normal Route service provider. That keeps the Quarx provider from taking over the default routing fallback.

**Comment by mlantz** [comment]
Thats great! I always place it after the `Package Service Providers...` comment, which is why I never could replicate it.
