### ISSUE TITLE
Docs: Complex setup route middleware

### ISSUE THREAD

**Issue by merijnvdk** [GrafiteInc/CMS#98]
In the docs:

> Then add to the Kernel Route Middleware:
> 'quarx' => \App\Http\Middleware\Quarx::class,
> 'quarx-api' => \App\Http\Middleware\QuarxApi::class,

But for the routes/quarx.php it seems you also need to add the following middleware:

        'quarx-language' => \App\Http\Middleware\QuarxLanguage::class,
        'quarx-analytics' => \Yab\Quarx\Middleware\QuarxAnalytics::class

To get it working I had to edit the routes\quarx.ph from: 

    Route::group(['namespace' => Quarx', 'middleware' => ['quarx-language', 'quarx-analytics']], function () {
 to:

    Route::group(['namespace' => 'App\Http\Controllers\Quarx', 'middleware' => ['quarx-language', 'quarx-analytics']], function () {

And offcource if your namespace is no longer \App then you need to edit all copied files to change the namespace.

Or am I doing something wrong here? I am trying to drop quarx into an existing project.

**Comment by ajoy39** [comment]
The documentation is a little out of date on the site but the readme for this project is accurate, I would follow the complex setup in this projects readme file

**Comment by merijnvdk** [comment]
Ah right, I see it has been changed indeed. Maybe add a comment in the site refering to the readme for latest instructions, if the site is often outdated.

**Comment by mlantz** [comment]
Docs on the site have been updated
