### ISSUE TITLE
Dashboard Checkboxes - Incorrect style applied (form-control)

### ISSUE THREAD

**Issue by joshua-p-williams** [GrafiteInc/CMS#99]
The checkboxes are being rendered with the form-control class applied, this is causing them to render incorrectly.
 
![checkboxstyle](https://user-images.githubusercontent.com/10605614/31923055-393382c2-b83e-11e7-927e-8ce5aaea0d33.png)

This is the default class applied by the FormMaker project see line 86 of [FormMaker.php](https://github.com/YABhq/FormMaker/blob/master/src/Services/FormMaker.php).

I don't know what the proper recommended fix would be (don't want to introduce any adverse effects), but if you wanted assistance on this, just point me in the correct direction and I'll work on a correction.

**Comment by mlantz** [comment]
Correctly in the latest FormMaker release - so you should be able to composer update and get rid of that bug
